name: terminal
author: Ajenti project
email: e@ajenti.org
url: http://ajenti.org
version: '0.32'
title: 'Terminal'
icon: terminal
dependencies:
    - !!python/object:aj.plugins.PluginDependency { plugin_name: core }
    - !!python/object:aj.plugins.PluginDependency { plugin_name: ace }
    - !!python/object:aj.plugins.OptionalPluginDependency { plugin_name: dashboard }
resources:
    - 'resources/css/terminal.less'
    - 'resources/js/module.coffee'
    - 'resources/js/routing.coffee'
    - 'resources/js/directives/terminal.coffee'
    - 'resources/js/controllers/index.controller.coffee'
    - 'resources/js/controllers/view.controller.coffee'
    - 'resources/js/controllers/widget.controller.coffee'
    - 'resources/js/services/terminals.service.coffee'
    - 'resources/partial/index.html'
    - 'resources/partial/view.html'
    - 'resources/partial/widget.html'
    - 'resources/partial/widget.config.html'
    - 'ng:ajenti.terminal'
