"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '22f229c7b6f9c4ab7a0362b3781856edc1fe4c22',
              'dirt': '',
              'latest_tag': 'flowtool-git-0.7.21',
              'latest_tag_commit': '22f229c7b6f9c4ab7a0362b3781856edc1fe4c22',
              'latest_tag_version': '0.7.21',
              'prefix': 'flowtool-git-',
              'prefix_tag_distances': {'flowtool-git-0.7.17': 137,
                                       'flowtool-git-0.7.18': 68,
                                       'flowtool-git-0.7.19': 2,
                                       'flowtool-git-0.7.20': 1,
                                       'flowtool-git-0.7.21': 0},
              'tag_version': {'normalized': '0.7.21',
                              'release': (0, 7, 21),
                              'version': '0.7.21'}},
 'version': '0.7.21'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
