"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '588bf70b4153d034450255ce81d2f668a526ed17',
              'dirt': '',
              'latest_tag': 'data-pypes-0.1.2',
              'latest_tag_commit': '588bf70b4153d034450255ce81d2f668a526ed17',
              'latest_tag_version': '0.1.2',
              'prefix': 'data-pypes-',
              'prefix_tag_distances': {'data-pypes-0.1.1': 2,
                                       'data-pypes-0.1.2': 0},
              'tag_version': {'normalized': '0.1.2',
                              'release': (0, 1, 2),
                              'version': '0.1.2'}},
 'version': '0.1.2'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
