"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'f42a44a4cac95af4ee6d5546afd13cd8ed275280',
              'dirt': '',
              'latest_tag': 'flowtool-base-0.7.54',
              'latest_tag_commit': 'f42a44a4cac95af4ee6d5546afd13cd8ed275280',
              'latest_tag_version': '0.7.54',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {'flowtool-base-0.7.51': 53,
                                       'flowtool-base-0.7.52': 29,
                                       'flowtool-base-0.7.53': 24,
                                       'flowtool-base-0.7.54': 0},
              'tag_version': {'normalized': '0.7.54',
                              'release': (0, 7, 54),
                              'version': '0.7.54'}},
 'version': '0.7.54'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
