
# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_status__'
]

__version__ = '1.0.3'
__version_post__ = '0'
__version_commit__ = '28869480'
__version_date__ = '2016-03-31 16:06:37 -0400'
__version_dirty__ = False
__build_date__ = '2016-03-31'
__build_time__ = '16:10:23.189888'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
