"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': 'a6db2f732732287569594bb73a879b87c71c7762',
              'dirt': '',
              'latest_tag': 'flowtool-githooks-0.7.23',
              'latest_tag_commit': 'a6db2f732732287569594bb73a879b87c71c7762',
              'latest_tag_version': '0.7.23',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {'flowtool-githooks-0.7.13': 122,
                                       'flowtool-githooks-0.7.14': 99,
                                       'flowtool-githooks-0.7.15': 53,
                                       'flowtool-githooks-0.7.16': 45,
                                       'flowtool-githooks-0.7.17': 44,
                                       'flowtool-githooks-0.7.18': 43,
                                       'flowtool-githooks-0.7.19': 40,
                                       'flowtool-githooks-0.7.20': 19,
                                       'flowtool-githooks-0.7.21': 6,
                                       'flowtool-githooks-0.7.22': 4,
                                       'flowtool-githooks-0.7.23': 0,
                                       'flowtool-githooks-demo-0.7.4': 93,
                                       'flowtool-githooks-demo-0.7.5': 92},
              'tag_version': {'normalized': '0.7.23',
                              'release': (0, 7, 23),
                              'version': '0.7.23'}},
 'version': '0.7.23'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
