
language: python
python: 2.7
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=2.7-1.4.20,coveralls
    - TOXENV=2.7-1.4.20-nocover
    - TOXENV=2.7-1.5.12,coveralls
    - TOXENV=2.7-1.5.12-nocover
    - TOXENV=2.7-1.6.11,coveralls
    - TOXENV=2.7-1.6.11-nocover
    - TOXENV=2.7-1.7.7,coveralls
    - TOXENV=2.7-1.7.7-nocover
    - TOXENV=2.7-1.8,coveralls
    - TOXENV=2.7-1.8-nocover
    - TOXENV=3.3-1.5.12,coveralls
    - TOXENV=3.3-1.5.12-nocover
    - TOXENV=3.3-1.6.11,coveralls
    - TOXENV=3.3-1.6.11-nocover
    - TOXENV=3.3-1.7.7,coveralls
    - TOXENV=3.3-1.7.7-nocover
    - TOXENV=3.3-1.8,coveralls
    - TOXENV=3.3-1.8-nocover
    - TOXENV=3.4-1.5.12,coveralls
    - TOXENV=3.4-1.5.12-nocover
    - TOXENV=3.4-1.6.11,coveralls
    - TOXENV=3.4-1.6.11-nocover
    - TOXENV=3.4-1.7.7,coveralls
    - TOXENV=3.4-1.7.7-nocover
    - TOXENV=3.4-1.8,coveralls
    - TOXENV=3.4-1.8-nocover
    - TOXENV=pypy-1.4.20,coveralls
    - TOXENV=pypy-1.4.20-nocover
    - TOXENV=pypy-1.5.12,coveralls
    - TOXENV=pypy-1.5.12-nocover
    - TOXENV=pypy-1.6.11,coveralls
    - TOXENV=pypy-1.6.11-nocover
    - TOXENV=pypy-1.7.7,coveralls
    - TOXENV=pypy-1.7.7-nocover
    - TOXENV=pypy-1.8,coveralls
    - TOXENV=pypy-1.8-nocover
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always
