# Generated by setup.py for PyBurst on 2016-03-22 18:46:47 +0000.

version = '0.1.0'
date = '2016-03-22 18:25:50 +0000'
release = False

git_hash = 'baf2ef19f6efe99c8d016647853111f862a3eb13'
git_branch = 'master'
git_tag = 'pyburst-0.1.0'
git_author = 'Chris Pankow <chris.pankow@ligo.org>'
git_committer = 'Chris Pankow <chris.pankow@ligo.org>'
git_status = 'UNCLEAN: Modified working tree'
git_builder = 'Chris Pankow <chris.pankow@ligo.org>'
git_build_date = '2016-03-22 18:46:47 +0000'
git_verbose_msg = """Branch: master
Tag: pyburst-0.1.0
Id: baf2ef19f6efe99c8d016647853111f862a3eb13
Builder: Chris Pankow <chris.pankow@ligo.org>
Build date: 2016-03-22 18:46:47 +0000
Repository status is UNCLEAN: Modified working tree"""