"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': u'95ddbc6f28a55a05c025a2f17adfd5655f380f46',
              'dirt': u'',
              'latest_tag': u'flowtool-gitflow-0.7.10',
              'latest_tag_commit': u'95ddbc6f28a55a05c025a2f17adfd5655f380f46',
              'latest_tag_version': u'0.7.10',
              'prefix': 'flowtool-gitflow-',
              'prefix_tag_distances': {u'flowtool-gitflow-0.7.10': 0,
                                       u'flowtool-gitflow-0.7.8': 29,
                                       u'flowtool-gitflow-0.7.9': 15},
              'tag_version': {'normalized': '0.7.10',
                              'release': (0, 7, 10),
                              'version': u'0.7.10'}},
 'version': u'0.7.10'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
