"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '68b36e040c19290719bc8091067318010cc62b6f',
              'dirt': '',
              'latest_tag': 'flowtool-python-0.7.28',
              'latest_tag_commit': '68b36e040c19290719bc8091067318010cc62b6f',
              'latest_tag_version': '0.7.28',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.11': 148,
                                       'flowtool-python-0.7.12': 143,
                                       'flowtool-python-0.7.13': 141,
                                       'flowtool-python-0.7.14': 50,
                                       'flowtool-python-0.7.15': 47,
                                       'flowtool-python-0.7.16': 46,
                                       'flowtool-python-0.7.17': 45,
                                       'flowtool-python-0.7.18': 41,
                                       'flowtool-python-0.7.19': 21,
                                       'flowtool-python-0.7.20': 19,
                                       'flowtool-python-0.7.21': 18,
                                       'flowtool-python-0.7.22': 17,
                                       'flowtool-python-0.7.23': 16,
                                       'flowtool-python-0.7.24': 12,
                                       'flowtool-python-0.7.25': 11,
                                       'flowtool-python-0.7.26': 9,
                                       'flowtool-python-0.7.27': 3,
                                       'flowtool-python-0.7.28': 0},
              'tag_version': {'normalized': '0.7.28',
                              'release': (0, 7, 28),
                              'version': '0.7.28'}},
 'version': '0.7.28'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
