"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '0e381d041719b9982ae9cc496fcfd8bb1ac38e99',
              'dirt': '',
              'latest_tag': 'flowtool-base-0.7.43',
              'latest_tag_commit': '0e381d041719b9982ae9cc496fcfd8bb1ac38e99',
              'latest_tag_version': '0.7.43',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {'flowtool-base-0.7.12': 255,
                                       'flowtool-base-0.7.13': 237,
                                       'flowtool-base-0.7.14': 235,
                                       'flowtool-base-0.7.15': 234,
                                       'flowtool-base-0.7.16': 233,
                                       'flowtool-base-0.7.17': 232,
                                       'flowtool-base-0.7.18': 230,
                                       'flowtool-base-0.7.19': 226,
                                       'flowtool-base-0.7.20': 221,
                                       'flowtool-base-0.7.21': 220,
                                       'flowtool-base-0.7.22': 219,
                                       'flowtool-base-0.7.23': 202,
                                       'flowtool-base-0.7.24': 198,
                                       'flowtool-base-0.7.25': 197,
                                       'flowtool-base-0.7.26': 196,
                                       'flowtool-base-0.7.27': 195,
                                       'flowtool-base-0.7.28': 194,
                                       'flowtool-base-0.7.29': 188,
                                       'flowtool-base-0.7.30': 187,
                                       'flowtool-base-0.7.31': 182,
                                       'flowtool-base-0.7.32': 177,
                                       'flowtool-base-0.7.33': 175,
                                       'flowtool-base-0.7.34': 172,
                                       'flowtool-base-0.7.35': 144,
                                       'flowtool-base-0.7.36': 137,
                                       'flowtool-base-0.7.37': 131,
                                       'flowtool-base-0.7.38': 127,
                                       'flowtool-base-0.7.39': 91,
                                       'flowtool-base-0.7.40': 79,
                                       'flowtool-base-0.7.41': 57,
                                       'flowtool-base-0.7.42': 35,
                                       'flowtool-base-0.7.43': 0},
              'tag_version': {'normalized': '0.7.43',
                              'release': (0, 7, 43),
                              'version': '0.7.43'}},
 'version': '0.7.43'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
