language: python
dist: trusty
sudo: required
cache: pip
python:
    - 2.7
    - 3.4
    - 3.5
addons:
  apt:
    packages:
    - mysql-server
    - redis-server
    - zookeeper
    - influxdb
    - mongodb
    - etcd
before_install:
  - curl 'https://git.ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc' | sudo apt-key add -
  - echo deb http://download.ceph.com/debian-hammer/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
  - sudo apt-get update -yq
  - sudo apt-get install -yq ceph
install: pip install tox-travis
script: travis_wait 20 tox -v
# notifications:
#  email:
#    - julien@danjou.info
