# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0003_auto_20160308_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='precondition',
            name='filename',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='filename',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='precondition',
            name='condition',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
