
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '3CFA3369D62E748D41C546F02C0CB00D'
    
_lr_action_items = {'WORD':([0,1,2,4,5,8,10,11,12,],[1,5,1,12,-6,1,1,1,-7,]),'FLOAT':([7,9,],[14,14,]),'LPAR':([0,2,8,10,11,],[2,2,2,2,2,]),'LT':([1,3,4,5,6,12,13,14,15,16,17,18,19,],[-9,9,-8,-6,9,-7,-10,-11,-5,9,-4,9,9,]),'RT':([1,3,4,5,6,12,13,14,15,16,17,18,19,],[-9,7,-8,-6,7,-7,-10,-11,-5,7,-4,7,7,]),'ANDNOT':([1,3,4,5,6,12,13,14,15,16,17,18,19,],[-9,8,-8,-6,8,-7,-10,-11,-5,8,-4,8,8,]),'OR':([1,3,4,5,6,12,13,14,15,16,17,18,19,],[-9,10,-8,-6,10,-7,-10,-11,-5,10,-4,10,10,]),'$end':([1,3,4,5,12,13,14,15,16,17,18,19,],[-9,0,-8,-6,-7,-10,-11,-5,-1,-4,-3,-2,]),'RPAR':([1,4,5,6,12,13,14,15,16,17,18,19,],[-9,-8,-6,13,-7,-10,-11,-5,-1,-4,-3,-2,]),'AND':([1,3,4,5,6,12,13,14,15,16,17,18,19,],[-9,11,-8,-6,11,-7,-10,-11,-5,11,-4,11,11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'list':([0,2,8,10,11,],[3,6,16,18,19,]),'freq':([7,9,],[15,17,]),'feature':([0,2,8,10,11,],[4,4,4,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> list","S'",1,None,None,None),
  ('list -> list ANDNOT list','list',3,'p_list_andnot','lexparser.py',67),
  ('list -> list AND list','list',3,'p_list_and','lexparser.py',71),
  ('list -> list OR list','list',3,'p_list_or','lexparser.py',76),
  ('list -> list LT freq','list',3,'p_list_lt','lexparser.py',81),
  ('list -> list RT freq','list',3,'p_list_rt','lexparser.py',85),
  ('feature -> WORD WORD','feature',2,'p_feature_words','lexparser.py',89),
  ('feature -> feature WORD','feature',2,'p_feature_words','lexparser.py',90),
  ('list -> feature','list',1,'p_list_feature','lexparser.py',94),
  ('list -> WORD','list',1,'p_list_feature','lexparser.py',95),
  ('list -> LPAR list RPAR','list',3,'p_list_expr','lexparser.py',101),
  ('freq -> FLOAT','freq',1,'p_freq_float','lexparser.py',105),
]
