
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "59407d37c6c7593eeeab5ed993929b24057b355a",
 "version": "0.0.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
