language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install zc.buildout
  - buildout -c qa.cfg
script:
  - bin/code-analysis
  - nosetests --with-coverage --cover-package=haproxy
after_success:
  - coveralls
