
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.2'
version_full = '59f97b08fd611f01e43ff9ed84e09672cea1851a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

