"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '6a54637d7662f13a4b67c816318853db7743cdf3',
              'dirt': '',
              'latest_tag': 'flowtool-demo-githooks-0.7.16',
              'latest_tag_commit': '6a54637d7662f13a4b67c816318853db7743cdf3',
              'latest_tag_version': '0.7.16',
              'prefix': 'flowtool-demo-githooks-',
              'prefix_tag_distances': {'flowtool-demo-githooks-0.7.12': 37,
                                       'flowtool-demo-githooks-0.7.13': 16,
                                       'flowtool-demo-githooks-0.7.14': 6,
                                       'flowtool-demo-githooks-0.7.15': 5,
                                       'flowtool-demo-githooks-0.7.16': 0},
              'tag_version': {'normalized': '0.7.16',
                              'release': (0, 7, 16),
                              'version': '0.7.16'}},
 'version': '0.7.16'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
