"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'f3b81ce845dcf7bc3b69ae47bfd761ed85e9fef0',
              'dirt': '',
              'latest_tag': 'flowtool-base-0.7.41',
              'latest_tag_commit': 'f3b81ce845dcf7bc3b69ae47bfd761ed85e9fef0',
              'latest_tag_version': '0.7.41',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {'flowtool-base-0.7.12': 198,
                                       'flowtool-base-0.7.13': 180,
                                       'flowtool-base-0.7.14': 178,
                                       'flowtool-base-0.7.15': 177,
                                       'flowtool-base-0.7.16': 176,
                                       'flowtool-base-0.7.17': 175,
                                       'flowtool-base-0.7.18': 173,
                                       'flowtool-base-0.7.19': 169,
                                       'flowtool-base-0.7.20': 164,
                                       'flowtool-base-0.7.21': 163,
                                       'flowtool-base-0.7.22': 162,
                                       'flowtool-base-0.7.23': 145,
                                       'flowtool-base-0.7.24': 141,
                                       'flowtool-base-0.7.25': 140,
                                       'flowtool-base-0.7.26': 139,
                                       'flowtool-base-0.7.27': 138,
                                       'flowtool-base-0.7.28': 137,
                                       'flowtool-base-0.7.29': 131,
                                       'flowtool-base-0.7.30': 130,
                                       'flowtool-base-0.7.31': 125,
                                       'flowtool-base-0.7.32': 120,
                                       'flowtool-base-0.7.33': 118,
                                       'flowtool-base-0.7.34': 115,
                                       'flowtool-base-0.7.35': 87,
                                       'flowtool-base-0.7.36': 80,
                                       'flowtool-base-0.7.37': 74,
                                       'flowtool-base-0.7.38': 70,
                                       'flowtool-base-0.7.39': 34,
                                       'flowtool-base-0.7.40': 22,
                                       'flowtool-base-0.7.41': 0},
              'tag_version': {'normalized': '0.7.41',
                              'release': (0, 7, 41),
                              'version': '0.7.41'}},
 'version': '0.7.41'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
