"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': 'b2b507b61a84085b90c2eb2a27fb1c45ed652061',
              'dirt': '',
              'latest_tag': 'flowtool-all-0.7.11',
              'latest_tag_commit': 'b2b507b61a84085b90c2eb2a27fb1c45ed652061',
              'latest_tag_version': '0.7.11',
              'prefix': 'flowtool-all-',
              'prefix_tag_distances': {'flowtool-all-0.7.10': 6,
                                       'flowtool-all-0.7.11': 0,
                                       'flowtool-all-0.7.8': 68,
                                       'flowtool-all-0.7.9': 28},
              'tag_version': {'normalized': '0.7.11',
                              'release': (0, 7, 11),
                              'version': '0.7.11'}},
 'version': '0.7.11'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
