"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': 'e1baccc985545cf714cf949ad2565a7b6812016e',
              'dirt': '',
              'latest_tag': 'flowtool-versioning-0.7.32',
              'latest_tag_commit': 'e1baccc985545cf714cf949ad2565a7b6812016e',
              'latest_tag_version': '0.7.32',
              'prefix': 'flowtool-versioning-',
              'prefix_tag_distances': {'flowtool-versioning-0.7.11': 86,
                                       'flowtool-versioning-0.7.12': 85,
                                       'flowtool-versioning-0.7.13': 84,
                                       'flowtool-versioning-0.7.14': 82,
                                       'flowtool-versioning-0.7.15': 81,
                                       'flowtool-versioning-0.7.16': 78,
                                       'flowtool-versioning-0.7.17': 76,
                                       'flowtool-versioning-0.7.18': 74,
                                       'flowtool-versioning-0.7.19': 73,
                                       'flowtool-versioning-0.7.20': 71,
                                       'flowtool-versioning-0.7.21': 68,
                                       'flowtool-versioning-0.7.22': 56,
                                       'flowtool-versioning-0.7.23': 49,
                                       'flowtool-versioning-0.7.24': 48,
                                       'flowtool-versioning-0.7.25': 46,
                                       'flowtool-versioning-0.7.26': 45,
                                       'flowtool-versioning-0.7.27': 35,
                                       'flowtool-versioning-0.7.28': 33,
                                       'flowtool-versioning-0.7.29': 30,
                                       'flowtool-versioning-0.7.30': 27,
                                       'flowtool-versioning-0.7.31': 26,
                                       'flowtool-versioning-0.7.32': 0},
              'tag_version': {'normalized': '0.7.32',
                              'release': (0, 7, 32),
                              'version': '0.7.32'}},
 'version': '0.7.32'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
