"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'tag_version': {'normalized': '0.7.3',
                 'release': (0, 7, 3),
                 'version': '0.7.3'},
 'vcs_info': {'commit': 'f342904dbcb0dbc5e0961817a01323c5c555dfd6',
              'dirt': '',
              'latest_tag': 'flowtool-git-0.7.3',
              'latest_tag_commit': 'f342904dbcb0dbc5e0961817a01323c5c555dfd6',
              'latest_tag_version': '0.7.3',
              'prefix': 'flowtool-git-',
              'prefix_tag_distances': {'flowtool-git-0.7.1': 14,
                                       'flowtool-git-0.7.2': 12,
                                       'flowtool-git-0.7.3': 0}},
 'version': '0.7.3'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', 'no_version')
