
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c303a4b1fa0e211e64e153cf6c61bc13cea11345",
 "version": "0.0.18-2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
