---
- hosts: all
  vars:
    include_vars_dir_paths:
      - "~/.osxstrap"
    include_vars_file_extension: "yml"
  roles:
    - role: jeremyltn.include-vars-dir
      tags: ['common','always']
    - role: jeremyltn.remote-vars
      tags: ['remote_vars']
    - role: jeremyltn.include-vars-dir
      tags: ['include_vars_dir']
    - role: jeremyltn.osx-software-update
      tags: ['software_update']
    - role: jeremyltn.homebrew
      tags: ['homebrew']
    - role: jeremyltn.osx-common-env
      tags: ['common_env']
    - role: jeremyltn.osx-oh-my-zsh
      tags: ['oh_my_zsh']
    - role: jeremyltn.osx-fish
      tags: ['fish']
    - role: jeremyltn.gitconfig
      tags: ['gitconfig']
    - role: jeremyltn.dotfiles
      tags: ['dotfiles']
    - role: jeremyltn.osx-defaults
      tags: ['defaults']
    - role: jeremyltn.osx-user-picture
      tags: ['user_picture']
    - role: jeremyltn.osx-computername
      tags: ['computername']
    - role: jeremyltn.osx-sudoers
      tags: ['sudoers']
    - role: jeremyltn.osx-sublimetext
      tags: ['sublimetext']
    - role: jeremyltn.osx-php
      tags: ['php']
    - role: jeremyltn.pip
      tags: ['pip']
    - role: jeremyltn.rbenv
      tags: ['rbenv']
    - role: jeremyltn.ruby-gems
      tags: ['ruby_gems']
    - role: jeremyltn.osx-node
      tags: ['node']
    - role: jeremyltn.git-repos
      tags: ['repos']
    - role: jeremyltn.osx-ssd
      tags: ['ssd']
