
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '3.4.1'
version_full = 'ac7d97e1e2d1c50b0424f5420472c5934060d0da'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

