"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '7ca5937b6ad75e45ec4e0b63a34ef3587822ae74',
              'dirt': '',
              'latest_tag': 'flowtool-python-0.7.15',
              'latest_tag_commit': '7ca5937b6ad75e45ec4e0b63a34ef3587822ae74',
              'latest_tag_version': '0.7.15',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.11': 101,
                                       'flowtool-python-0.7.12': 96,
                                       'flowtool-python-0.7.13': 94,
                                       'flowtool-python-0.7.14': 3,
                                       'flowtool-python-0.7.15': 0},
              'tag_version': {'normalized': '0.7.15',
                              'release': (0, 7, 15),
                              'version': '0.7.15'}},
 'version': '0.7.15'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
