
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c9e69af28e5dd0a128e90e7860a38e971092efbb",
 "version": "0.2.post34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
