# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0004_auto_20160308_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='current_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflowapp.State'),
        ),
    ]
