
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "913799a7c457f359eb2ddaa1178beb0edcbd1f0e",
 "version": "1.0.0.post.dev74"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
