"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '430920e644f7338422391f3694e0b903ab3eae6a',
              'dirt': '',
              'latest_tag': 'flowtool-git-0.7.22',
              'latest_tag_commit': '430920e644f7338422391f3694e0b903ab3eae6a',
              'latest_tag_version': '0.7.22',
              'prefix': 'flowtool-git-',
              'prefix_tag_distances': {'flowtool-git-0.7.19': 23,
                                       'flowtool-git-0.7.20': 22,
                                       'flowtool-git-0.7.21': 21,
                                       'flowtool-git-0.7.22': 0},
              'tag_version': {'normalized': '0.7.22',
                              'release': (0, 7, 22),
                              'version': '0.7.22'}},
 'version': '0.7.22'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
