# Docker Infrastructure (see http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/ )
sudo: false

language: python
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=pep8
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.4
      env: TOX_ENV=py34
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
