
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7464eb2f7f5ebb693f81f0e490620e7e57b6e176",
 "version": "0.2.post30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
