
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.4.1'
version_full = '5d4cbe9f113fb63ba2c9c9a067b2f59157188d39'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

