"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '30e4a9db29f846a9af8f5ee3bd0ab6e6255f272d',
              'dirt': '',
              'latest_tag': 'flowtool-git-0.7.15',
              'latest_tag_commit': '30e4a9db29f846a9af8f5ee3bd0ab6e6255f272d',
              'latest_tag_version': '0.7.15',
              'prefix': 'flowtool-git-',
              'prefix_tag_distances': {'flowtool-git-0.7.1': 174,
                                       'flowtool-git-0.7.10': 85,
                                       'flowtool-git-0.7.11': 74,
                                       'flowtool-git-0.7.12': 72,
                                       'flowtool-git-0.7.13': 70,
                                       'flowtool-git-0.7.14': 69,
                                       'flowtool-git-0.7.15': 0,
                                       'flowtool-git-0.7.2': 172,
                                       'flowtool-git-0.7.3': 160,
                                       'flowtool-git-0.7.4': 151,
                                       'flowtool-git-0.7.5': 149,
                                       'flowtool-git-0.7.6': 145,
                                       'flowtool-git-0.7.7': 124,
                                       'flowtool-git-0.7.8': 123,
                                       'flowtool-git-0.7.9': 100},
              'tag_version': {'normalized': '0.7.15',
                              'release': (0, 7, 15),
                              'version': '0.7.15'}},
 'version': '0.7.15'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
