
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a539956f77285061bd93f26a1cdf33b7fa1132d5",
 "version": "1.1.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
