about:
  home: https://github.com/EelcoHoogendoorn/Numpy_arraysetops_EP
  license: Freely Distributable
  summary: Numpy indexing based extensions, such as group_by
build:
  noarch_python: true
  number: 1
package:
  name: numpy-indexed
  version: 0.2.11
requirements:
  build:
  - python
  - numpy
  - pyyaml 3.11*
  - future 0.15*
  - pypandoc
  run:
  - python
  - numpy
  - future 0.15*
source:
  path: ..
test:
  commands:
  - py.test --pyargs numpy_indexed
  imports:
  - numpy_indexed
  requires:
  - pytest >=2.8.4,<2.9
