"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '8bc2ab9f361565eb4da0205d501c2b7450160f12',
              'dirt': '',
              'latest_tag': 'flowtool-base-0.7.53',
              'latest_tag_commit': '8bc2ab9f361565eb4da0205d501c2b7450160f12',
              'latest_tag_version': '0.7.53',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {'flowtool-base-0.7.49': 84,
                                       'flowtool-base-0.7.50': 30,
                                       'flowtool-base-0.7.51': 29,
                                       'flowtool-base-0.7.52': 5,
                                       'flowtool-base-0.7.53': 0},
              'tag_version': {'normalized': '0.7.53',
                              'release': (0, 7, 53),
                              'version': '0.7.53'}},
 'version': '0.7.53'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
