"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '532c6d1949f472a33b26e393e263b1d5af979e69',
              'dirt': '',
              'latest_tag': 'flowtool-python-0.7.24',
              'latest_tag_commit': '532c6d1949f472a33b26e393e263b1d5af979e69',
              'latest_tag_version': '0.7.24',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.11': 136,
                                       'flowtool-python-0.7.12': 131,
                                       'flowtool-python-0.7.13': 129,
                                       'flowtool-python-0.7.14': 38,
                                       'flowtool-python-0.7.15': 35,
                                       'flowtool-python-0.7.16': 34,
                                       'flowtool-python-0.7.17': 33,
                                       'flowtool-python-0.7.18': 29,
                                       'flowtool-python-0.7.19': 9,
                                       'flowtool-python-0.7.20': 7,
                                       'flowtool-python-0.7.21': 6,
                                       'flowtool-python-0.7.22': 5,
                                       'flowtool-python-0.7.23': 4,
                                       'flowtool-python-0.7.24': 0},
              'tag_version': {'normalized': '0.7.24',
                              'release': (0, 7, 24),
                              'version': '0.7.24'}},
 'version': '0.7.24'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
