__version__ = "0.5.39"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v0.5.39)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'b1e5b04abb0fc91cac3808e3c5b59fcfcb4121fd'
__git_head_subject__ = 'Finished Release v0.5.39'
__git_head_message__ = ''
__git_dirty_diff__ = ''
__git_commit_date__ = '2016-04-03 12:56:10'
