"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '61371a3e5938357d6da01cc7bb8f593ca6599d34',
              'dirt': '',
              'latest_tag': 'flowtool-demo-githooks-0.7.21',
              'latest_tag_commit': '61371a3e5938357d6da01cc7bb8f593ca6599d34',
              'latest_tag_version': '0.7.21',
              'prefix': 'flowtool-demo-githooks-',
              'prefix_tag_distances': {'flowtool-demo-githooks-0.7.18': 12,
                                       'flowtool-demo-githooks-0.7.19': 9,
                                       'flowtool-demo-githooks-0.7.20': 5,
                                       'flowtool-demo-githooks-0.7.21': 0},
              'tag_version': {'normalized': '0.7.21',
                              'release': (0, 7, 21),
                              'version': '0.7.21'}},
 'version': '0.7.21'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
