"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '34e03b00183531263c5cb20255759bc65c7b26b4',
              'dirt': '',
              'latest_tag': 'flowtool-base-0.7.55',
              'latest_tag_commit': '34e03b00183531263c5cb20255759bc65c7b26b4',
              'latest_tag_version': '0.7.55',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {'flowtool-base-0.7.52': 30,
                                       'flowtool-base-0.7.53': 25,
                                       'flowtool-base-0.7.54': 1,
                                       'flowtool-base-0.7.55': 0},
              'tag_version': {'normalized': '0.7.55',
                              'release': (0, 7, 55),
                              'version': '0.7.55'}},
 'version': '0.7.55'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
