"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'f7bd9274bc41b05e9b14bdbd266ccd6489612789',
              'dirt': '',
              'latest_tag': 'flowtool-gitflow-0.7.18',
              'latest_tag_commit': 'f7bd9274bc41b05e9b14bdbd266ccd6489612789',
              'latest_tag_version': '0.7.18',
              'prefix': 'flowtool-gitflow-',
              'prefix_tag_distances': {'flowtool-gitflow-0.7.16': 167,
                                       'flowtool-gitflow-0.7.17': 1,
                                       'flowtool-gitflow-0.7.18': 0},
              'tag_version': {'normalized': '0.7.18',
                              'release': (0, 7, 18),
                              'version': '0.7.18'}},
 'version': '0.7.18'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
