# This file was auto-generated by salt's setup on Monday, 04 April 2016 @ 21:04:18 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2016, 3, 0, 0, 2, 0, None)
