# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import microbot.validators


class Migration(migrations.Migration):

    dependencies = [
        ('microbot', '0014_chatstate_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(db_index=True, help_text='Set token provided by Telegram API.', max_length=100, validators=[microbot.validators.validate_token], verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='pattern',
            field=models.CharField(help_text='Regular expression the Handler will be triggered.', max_length=255, validators=[microbot.validators.validate_pattern], verbose_name='Pattern'),
        ),
        migrations.AlterField(
            model_name='headerparam',
            name='value_template',
            field=models.CharField(help_text='Set the value of the parameter. A jinja2 template.', max_length=255, validators=[microbot.validators.validate_template], verbose_name='Value template'),
        ),
        migrations.AlterField(
            model_name='request',
            name='url_template',
            field=models.CharField(help_text='Set the url to request. A jinja2 template.', max_length=255, validators=[microbot.validators.validate_template], verbose_name='Url template'),
        ),
        migrations.AlterField(
            model_name='response',
            name='keyboard_template',
            field=models.TextField(blank=True, help_text='Template to generate keyboard response. In jinja2.', null=True, validators=[microbot.validators.validate_template, microbot.validators.validate_telegram_keyboard], verbose_name='Keyboard template'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text_template',
            field=models.TextField(help_text='Template to generate text response. In jinja2.', validators=[microbot.validators.validate_template, microbot.validators.validate_telegram_text_html], verbose_name='Text template'),
        ),
        migrations.AlterField(
            model_name='urlparam',
            name='value_template',
            field=models.CharField(help_text='Set the value of the parameter. A jinja2 template.', max_length=255, validators=[microbot.validators.validate_template], verbose_name='Value template'),
        ),
    ]
