"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '5df4637aeb634a411d32cb2b98f16371a091bf73',
              'dirt': '',
              'latest_tag': 'flowtool-demo-githooks-0.7.22',
              'latest_tag_commit': '5df4637aeb634a411d32cb2b98f16371a091bf73',
              'latest_tag_version': '0.7.22',
              'prefix': 'flowtool-demo-githooks-',
              'prefix_tag_distances': {'flowtool-demo-githooks-0.7.19': 58,
                                       'flowtool-demo-githooks-0.7.20': 54,
                                       'flowtool-demo-githooks-0.7.21': 49,
                                       'flowtool-demo-githooks-0.7.22': 0},
              'tag_version': {'normalized': '0.7.22',
                              'release': (0, 7, 22),
                              'version': '0.7.22'}},
 'version': '0.7.22'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
