"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': u'fe3f391143eae204b615c915cf19602cb73cf291',
              'dirt': u'',
              'latest_tag': u'flowtool-git-0.7.6',
              'latest_tag_commit': u'fe3f391143eae204b615c915cf19602cb73cf291',
              'latest_tag_version': u'0.7.6',
              'prefix': 'flowtool-git-',
              'prefix_tag_distances': {u'flowtool-git-0.7.1': 29,
                                       u'flowtool-git-0.7.2': 27,
                                       u'flowtool-git-0.7.3': 15,
                                       u'flowtool-git-0.7.4': 6,
                                       u'flowtool-git-0.7.5': 4,
                                       u'flowtool-git-0.7.6': 0},
              'tag_version': {'normalized': '0.7.6',
                              'release': (0, 7, 6),
                              'version': u'0.7.6'}},
 'version': u'0.7.6'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
