"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '318594379c67350116dba2383de57f08c71978b6',
              'dirt': '',
              'latest_tag': 'flowtool-githooks-0.7.18',
              'latest_tag_commit': '318594379c67350116dba2383de57f08c71978b6',
              'latest_tag_version': '0.7.18',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {'flowtool-githooks-0.7.17': 1,
                                       'flowtool-githooks-0.7.18': 0},
              'tag_version': {'normalized': '0.7.18',
                              'release': (0, 7, 18),
                              'version': '0.7.18'}},
 'version': '0.7.18'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
