"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'f9ece622deb68725eb2cdc07d7ecf483bcbf9746',
              'dirt': '',
              'latest_tag': 'data-pypes-0.1.4',
              'latest_tag_commit': 'f9ece622deb68725eb2cdc07d7ecf483bcbf9746',
              'latest_tag_version': '0.1.4',
              'prefix': 'data-pypes-',
              'prefix_tag_distances': {'data-pypes-0.1.1': 9,
                                       'data-pypes-0.1.2': 7,
                                       'data-pypes-0.1.3': 5,
                                       'data-pypes-0.1.4': 0},
              'tag_version': {'normalized': '0.1.4',
                              'release': (0, 1, 4),
                              'version': '0.1.4'}},
 'version': '0.1.4'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
