
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2c4b27e550f609deada4035a7fc065f218d15ff8",
 "version": "1.0.0.post.dev118"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
