language: python
sudo: false
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
addons:
  apt:
    packages:
      - graphviz
install:
    - pip install coverage coveralls flake8 -e .
before_script:
    - make lint
script:
    - coverage run --source=objgraph tests.py
after_success:
    - coveralls
notifications:
    email: false
