"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': u'2195a152602cf6b5b095b6e51b15b295bcb72c6b',
              'dirt': u'',
              'latest_tag': u'flowtool-versioning-0.7.18',
              'latest_tag_commit': u'2195a152602cf6b5b095b6e51b15b295bcb72c6b',
              'latest_tag_version': u'0.7.18',
              'prefix': 'flowtool-versioning-',
              'prefix_tag_distances': {u'flowtool-versioning-0.7.11': 12,
                                       u'flowtool-versioning-0.7.12': 11,
                                       u'flowtool-versioning-0.7.13': 10,
                                       u'flowtool-versioning-0.7.14': 8,
                                       u'flowtool-versioning-0.7.15': 7,
                                       u'flowtool-versioning-0.7.16': 4,
                                       u'flowtool-versioning-0.7.17': 2,
                                       u'flowtool-versioning-0.7.18': 0},
              'tag_version': {'normalized': '0.7.18',
                              'release': (0, 7, 18),
                              'version': u'0.7.18'}},
 'version': u'0.7.18'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
