"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': 'c3701e9cfaac96a480f53422917802a635bfcfcc',
              'dirt': '',
              'latest_tag': 'flowtool-all-0.7.9',
              'latest_tag_commit': 'c3701e9cfaac96a480f53422917802a635bfcfcc',
              'latest_tag_version': '0.7.9',
              'prefix': 'flowtool-all-',
              'prefix_tag_distances': {'flowtool-all-0.7.7': 50,
                                       'flowtool-all-0.7.8': 40,
                                       'flowtool-all-0.7.9': 0},
              'tag_version': {'normalized': '0.7.9',
                              'release': (0, 7, 9),
                              'version': '0.7.9'}},
 'version': '0.7.9'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
