# https://travis-ci.org/#!/jaraco/keyring
#

language: python

matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.2
        - os: linux
          python: 3.3
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: osx
          language: generic

# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 -m venv /tmp/.env; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source /tmp/.env/bin/activate; fi

script:
  - pip install -U pytest
  - python setup.py test --addopts="-rs -v"
