
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.11.1'
version_full = '028a307959db50a8271133ed8b991d75c7e2e503'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

