
# This file was generated by 'versioneer.py' (0.13+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.4'
version_full = 'bf12824acdb6ff8c9b942a89a5e52ea9951f6d29'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

