
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.2'
version_full = 'ebf0aa4ebbc3be433918a44d0b24dcb9b379bc70'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

