language: python
python:
  - '2.7'

install:
  - pip install tox

script: tox -r
deploy:
  provider: pypi
  user: internaphosting
  password:
    secure: CKW0Ut7snv41yzOGifZ0FeXz8KIZdXsyylM0h+alGd0fJpWGu3klykq9pJWEDt3iOaHQ3cQrJEX4MUAGq9LXyPF/SMD6IDHapJ0+yZ/Wy+YF6+aQnViathG47oYz6cVytILmtL2M442TFKMcvlmHG+/Ast6zkVCzikyf5ZWA8uikNY8raXd4EsUQxY+sKyGmONjIyg8rZ8FWKN2DUeMutRpC/Yy/tIyzUW13v1Y6WeTZNivMa9cI/wmGawtMYb5ZQ2wvUw9NoO4zb7i1rZ0X7gOZHP0zr2nM7DgsIeieWk+kMxACJK8N+LmDSny80ZYBkj+DVwXqnu7FthHPiqCf9ohFIAn9PKM0qge2/mWAcbAWiJwFNlogloANpig/fDwLgNiNjc8lcCt9Zj0KgPUZjKwXSI6IU9xtF91QEe8KFeHt4C+oRThvPhKE8OZJXfufazB9pcheqknEZUi7ksNIw/MEtGI3r+STthR9yE3Ya+jcDhCm7pVYmN2MqdH6+gVjyDNF/aBZjXzvAP3fDVAdQjVAldPRsNOxv6KWaIyb2DY2uR1z3KvU71BPYotUiUfxfnJvWWlzrmpGPxIHWraYScdK+lcWuN6bFN2BnhYnThshXoMBEFzIC0byyzWUbjI45aBX1loXmKT4niMVZdIg4Dcmalvf0MMstpsEzHYsEyU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: internap/steelwool
