# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('microbot', '0009_auto_20160330_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='created',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='modified',
        ),
        migrations.AddField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 30, 10, 53, 59, 424826, tzinfo=utc), verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 30, 10, 54, 5, 828741, tzinfo=utc), verbose_name='Date updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 30, 10, 54, 15, 601452, tzinfo=utc), verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 30, 10, 54, 19, 343275, tzinfo=utc), verbose_name='Date updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environmentvar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 30, 10, 54, 25, 822994, tzinfo=utc), verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environmentvar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 30, 10, 54, 32, 495298, tzinfo=utc), verbose_name='Date updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 30, 10, 54, 37, 143361, tzinfo=utc), verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 30, 10, 54, 39, 63364, tzinfo=utc), verbose_name='Date updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headerparam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 30, 10, 54, 41, 575297, tzinfo=utc), verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headerparam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 30, 10, 54, 45, 935261, tzinfo=utc), verbose_name='Date updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 30, 10, 54, 48, 191018, tzinfo=utc), verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 30, 10, 54, 50, 111568, tzinfo=utc), verbose_name='Date updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 30, 10, 54, 52, 719225, tzinfo=utc), verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 30, 10, 54, 54, 263661, tzinfo=utc), verbose_name='Date updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 30, 10, 54, 58, 14929, tzinfo=utc), verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 30, 10, 55, 0, 111492, tzinfo=utc), verbose_name='Date updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 30, 10, 55, 1, 655098, tzinfo=utc), verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 30, 10, 55, 3, 335435, tzinfo=utc), verbose_name='Date updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 30, 10, 55, 4, 798581, tzinfo=utc), verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 30, 10, 55, 6, 175103, tzinfo=utc), verbose_name='Date updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlparam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 30, 10, 55, 7, 630619, tzinfo=utc), verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlparam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 30, 10, 55, 9, 247434, tzinfo=utc), verbose_name='Date updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatstate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='environmentvar',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='handler',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='headerparam',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hook',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='urlparam',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
