"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': 'cacbfc8a6703694640b9f76525e79df932d20178',
              'dirt': '',
              'latest_tag': 'flowtool-releasing-0.7.6',
              'latest_tag_commit': 'cacbfc8a6703694640b9f76525e79df932d20178',
              'latest_tag_version': '0.7.6',
              'prefix': 'flowtool-releasing-',
              'prefix_tag_distances': {'flowtool-releasing-0.7.5': 1,
                                       'flowtool-releasing-0.7.6': 0},
              'tag_version': {'normalized': '0.7.6',
                              'release': (0, 7, 6),
                              'version': '0.7.6'}},
 'version': '0.7.6'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
