
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c878f8069b769078e8f3174fc215172203a2568d",
 "version": "0.0.17.post2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
