# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0009_auto_20160310_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='is_automated',
            field=models.BooleanField(default=False),
        ),
    ]
