"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '105d5465568a0ba8fd77d3c29ea38ed3acddbee4',
              'dirt': '',
              'latest_tag': 'flowtool-git-0.7.14',
              'latest_tag_commit': '105d5465568a0ba8fd77d3c29ea38ed3acddbee4',
              'latest_tag_version': '0.7.14',
              'prefix': 'flowtool-git-',
              'prefix_tag_distances': {'flowtool-git-0.7.10': 16,
                                       'flowtool-git-0.7.11': 5,
                                       'flowtool-git-0.7.12': 3,
                                       'flowtool-git-0.7.13': 1,
                                       'flowtool-git-0.7.14': 0,
                                       'flowtool-git-0.7.7': 55,
                                       'flowtool-git-0.7.8': 54,
                                       'flowtool-git-0.7.9': 31},
              'tag_version': {'normalized': '0.7.14',
                              'release': (0, 7, 14),
                              'version': '0.7.14'}},
 'version': '0.7.14'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
