"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': u'497688546cf76ca51de9ea476677fc460d248632',
              'dirt': u'',
              'latest_tag': u'flowtool-git-0.7.8',
              'latest_tag_commit': u'497688546cf76ca51de9ea476677fc460d248632',
              'latest_tag_version': u'0.7.8',
              'prefix': 'flowtool-git-',
              'prefix_tag_distances': {u'flowtool-git-0.7.1': 51,
                                       u'flowtool-git-0.7.2': 49,
                                       u'flowtool-git-0.7.3': 37,
                                       u'flowtool-git-0.7.4': 28,
                                       u'flowtool-git-0.7.5': 26,
                                       u'flowtool-git-0.7.6': 22,
                                       u'flowtool-git-0.7.7': 1,
                                       u'flowtool-git-0.7.8': 0},
              'tag_version': {'normalized': '0.7.8',
                              'release': (0, 7, 8),
                              'version': u'0.7.8'}},
 'version': u'0.7.8'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
