"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '3d9391a38468e3c92135bc1fd1f1a28f11020362',
              'dirt': '',
              'latest_tag': 'flowtool-githooks-0.7.17',
              'latest_tag_commit': '3d9391a38468e3c92135bc1fd1f1a28f11020362',
              'latest_tag_version': '0.7.17',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {'flowtool-githooks-0.7.13': 78,
                                       'flowtool-githooks-0.7.14': 55,
                                       'flowtool-githooks-0.7.15': 9,
                                       'flowtool-githooks-0.7.16': 1,
                                       'flowtool-githooks-0.7.17': 0},
              'tag_version': {'normalized': '0.7.17',
                              'release': (0, 7, 17),
                              'version': '0.7.17'}},
 'version': '0.7.17'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
