ALWAYS_FIRST = ('__future__',)

STANDARD_MODULES = (
    'abc', 'aifc', 'antigravity', 'anydbm', 'argparse', 'array', 'ast',
    'asynchat', 'asyncio', 'asyncore', 'atexit', 'audiodev', 'audioop',
    'base64', 'BaseHTTPServer', 'Bastion', 'bdb', 'binascii', 'binhex',
    'bisect', 'bsddb', 'builtins', 'bz2', 'calendar', 'cgi', 'CGIHTTPServer',
    'cgitb', 'chunk', 'cmath', 'cmd', 'code', 'codecs', 'codeop',
    'collections', 'colorsys', 'commands', 'compileall', 'compiler',
    'concurrent', 'configparser', 'ConfigParser', 'contextlib', 'Cookie',
    'cookielib', 'copy', 'copy_reg', 'copyreg', 'cProfile', 'crypt', 'csv',
    'ctypes', 'curses', 'datetime', 'dbhash', 'dbm', 'decimal', 'difflib',
    'dircache', 'dis', 'distutils', 'doctest', 'DocXMLRPCServer', 'dumbdbm',
    'dummy_thread', 'dummy_threading', 'email', 'encodings', 'ensurepip',
    'enum', 'errno', 'faulthandler', 'fcntl', 'filecmp', 'fileinput',
    'fnmatch', 'formatter', 'fpectl', 'fpformat', 'fractions', 'ftplib',
    'functools', 'gc', 'genericpath', 'getopt', 'getpass', 'gettext', 'glob',
    'grp', 'gzip', 'hashlib', 'heapq', 'hmac', 'hotshot', 'html',
    'htmlentitydefs', 'htmllib', 'HTMLParser', 'http', 'httplib', 'idlelib',
    'ihooks', 'imaplib', 'imghdr', 'imp', 'importlib', 'imputil', 'inspect',
    'io', 'ipaddress', 'itertools', 'json', 'keyword', 'lib2to3', 'lib-tk',
    'linecache', 'locale', 'logging', 'lzma', 'macpath', 'macurl2path',
    'mailbox', 'mailcap', 'markupbase', 'marshal', 'math', 'md5', 'mhlib',
    'mimetools', 'mimetypes', 'MimeWriter', 'mimify', 'mmap', 'modulefinder',
    'msilib', 'msvcrt', 'multifile', 'multiprocessing', 'mutex', 'netrc',
    'new', 'nis', 'nntplib', 'ntpath', 'nturl2path', 'numbers', 'opcode',
    'operator', 'optparse', 'os', 'os2emxpath', 'ossaudiodev', 'parser',
    'pathlib', 'pdb', 'pickle', 'pickletools', 'pipes', 'pkgutil', 'platform',
    'plistlib', 'popen2', 'poplib', 'posix', 'posixfile', 'posixpath',
    'pprint', 'profile', 'pstats', 'pty', 'pwd', 'pyclbr', 'py_compile',
    'pydoc', 'pydoc_data', 'queue', 'Queue', 'quopri', 'random', 're',
    'readline', 'repr', 'reprlib', 'resource', 'rexec', 'rfc822',
    'rlcompleter', 'robotparser', 'runpy', 'sched', 'select', 'selectors',
    'sets', 'sgmllib', 'sha', 'shelve', 'shlex', 'shutil', 'signal',
    'SimpleHTTPServer', 'SimpleXMLRPCServer', 'site', 'site-packages', 'smtpd',
    'smtplib', 'sndhdr', 'socket', 'socketserver', 'SocketServer', 'spwd',
    'sqlite3', 'sre', 'sre_compile', 'sre_constants', 'sre_parse', 'ssl',
    'stat', 'statistics', 'statvfs', 'string', 'StringIO', 'stringold',
    'stringprep', 'struct', 'subprocess', 'sunau', 'sunaudio', 'symbol',
    'symtable', 'sys', 'sysconfig', 'syslog', 'tabnanny', 'tarfile',
    'telnetlib', 'tempfile', 'termios', 'test', 'textwrap', 'this',
    'threading', 'time', 'timeit', 'tkinter', 'toaiff', 'token', 'tokenize',
    'trace', 'traceback', 'tracemalloc', 'tty', 'turtle', 'turtledemo',
    'types', 'typing', 'unicodedata', 'unittest', 'urllib', 'urllib2',
    'urlparse', 'user', 'UserDict', 'UserList', 'UserString', 'uu', 'uuid',
    'venv', 'warnings', 'wave', 'weakref', 'webbrowser', 'whichdb', 'winreg',
    'winsound', 'wsgiref', 'xdrlib', 'xml', 'xmllib', 'xmlrpc', 'xmlrpclib',
    'zipapp', 'zipfile', 'zipimport', 'zlib'
)
