"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '60de4e117a4dcd4169de0713bb83ea770f53edba',
              'dirt': '',
              'latest_tag': 'flowtool-versioning-0.7.40',
              'latest_tag_commit': '60de4e117a4dcd4169de0713bb83ea770f53edba',
              'latest_tag_version': '0.7.40',
              'prefix': 'flowtool-versioning-',
              'prefix_tag_distances': {'flowtool-versioning-0.7.11': 242,
                                       'flowtool-versioning-0.7.12': 241,
                                       'flowtool-versioning-0.7.13': 240,
                                       'flowtool-versioning-0.7.14': 238,
                                       'flowtool-versioning-0.7.15': 237,
                                       'flowtool-versioning-0.7.16': 234,
                                       'flowtool-versioning-0.7.17': 232,
                                       'flowtool-versioning-0.7.18': 230,
                                       'flowtool-versioning-0.7.19': 229,
                                       'flowtool-versioning-0.7.20': 227,
                                       'flowtool-versioning-0.7.21': 224,
                                       'flowtool-versioning-0.7.22': 212,
                                       'flowtool-versioning-0.7.23': 205,
                                       'flowtool-versioning-0.7.24': 204,
                                       'flowtool-versioning-0.7.25': 202,
                                       'flowtool-versioning-0.7.26': 201,
                                       'flowtool-versioning-0.7.27': 191,
                                       'flowtool-versioning-0.7.28': 189,
                                       'flowtool-versioning-0.7.29': 186,
                                       'flowtool-versioning-0.7.30': 183,
                                       'flowtool-versioning-0.7.31': 182,
                                       'flowtool-versioning-0.7.32': 156,
                                       'flowtool-versioning-0.7.33': 75,
                                       'flowtool-versioning-0.7.34': 59,
                                       'flowtool-versioning-0.7.35': 21,
                                       'flowtool-versioning-0.7.36': 11,
                                       'flowtool-versioning-0.7.37': 7,
                                       'flowtool-versioning-0.7.38': 4,
                                       'flowtool-versioning-0.7.39': 1,
                                       'flowtool-versioning-0.7.40': 0},
              'tag_version': {'normalized': '0.7.40',
                              'release': (0, 7, 40),
                              'version': '0.7.40'}},
 'version': '0.7.40'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
