"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '98696b5665ab0acd1aed5099ad86e3ade13c7f7e',
              'dirt': '',
              'latest_tag': 'flowtool-versioning-0.7.28',
              'latest_tag_commit': '98696b5665ab0acd1aed5099ad86e3ade13c7f7e',
              'latest_tag_version': '0.7.28',
              'prefix': 'flowtool-versioning-',
              'prefix_tag_distances': {'flowtool-versioning-0.7.20': 38,
                                       'flowtool-versioning-0.7.21': 35,
                                       'flowtool-versioning-0.7.22': 23,
                                       'flowtool-versioning-0.7.23': 16,
                                       'flowtool-versioning-0.7.24': 15,
                                       'flowtool-versioning-0.7.25': 13,
                                       'flowtool-versioning-0.7.26': 12,
                                       'flowtool-versioning-0.7.27': 2,
                                       'flowtool-versioning-0.7.28': 0},
              'tag_version': {'normalized': '0.7.28',
                              'release': (0, 7, 28),
                              'version': '0.7.28'}},
 'version': '0.7.28'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
