
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "eb4e99f82fe325a274de18bf6eaf09ac05b145b5",
 "version": "v0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
