language: python

branches:
  only:
    - master

before_install:
  - deactivate
  - sudo apt-get install -y zlib1g-dev liblzma-dev libbz2-dev libxml2-dev nettle-dev libattr1-dev libacl1-dev
  - wget http://libarchive.org/downloads/libarchive-3.1.2.tar.gz
  - tar -xf libarchive-3.1.2.tar.gz && cd libarchive-3.1.2 && ./configure --disable-bsdcpio --disable-bsdtar && make && sudo make install && cd ..

install:
  - ~/virtualenv/python2.7/bin/pip install -r requirements_tests.txt
  - ~/virtualenv/python3.4/bin/pip install -r requirements_tests.txt

script:
  - ~/virtualenv/python2.7/bin/py.test -s -vv --cov libarchive ./tests
  - ~/virtualenv/python2.7/bin/flake8 libarchive tests
  - ~/virtualenv/python3.4/bin/py.test -s -vv --cov libarchive ./tests
  - ~/virtualenv/python3.4/bin/flake8 libarchive tests

notifications:
  email: false
