"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'c781a6bb5f8504f9f2de0d89496cfa93e82b3ef9',
              'dirt': '',
              'latest_tag': 'flowtool-demo-githooks-0.7.14',
              'latest_tag_commit': 'c781a6bb5f8504f9f2de0d89496cfa93e82b3ef9',
              'latest_tag_version': '0.7.14',
              'prefix': 'flowtool-demo-githooks-',
              'prefix_tag_distances': {'flowtool-demo-githooks-0.7.10': 52,
                                       'flowtool-demo-githooks-0.7.11': 40,
                                       'flowtool-demo-githooks-0.7.12': 31,
                                       'flowtool-demo-githooks-0.7.13': 10,
                                       'flowtool-demo-githooks-0.7.14': 0},
              'tag_version': {'normalized': '0.7.14',
                              'release': (0, 7, 14),
                              'version': '0.7.14'}},
 'version': '0.7.14'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
