# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='playlists',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', to='sql_testapp.Track'),
        ),
    ]
