"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'daf503e45a0ffa0844759252ccdd1c8a16e5e798',
              'dirt': '',
              'latest_tag': 'flowtool-python-0.7.42',
              'latest_tag_commit': 'daf503e45a0ffa0844759252ccdd1c8a16e5e798',
              'latest_tag_version': '0.7.42',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.11': 276,
                                       'flowtool-python-0.7.12': 271,
                                       'flowtool-python-0.7.13': 269,
                                       'flowtool-python-0.7.14': 178,
                                       'flowtool-python-0.7.15': 175,
                                       'flowtool-python-0.7.16': 174,
                                       'flowtool-python-0.7.17': 173,
                                       'flowtool-python-0.7.18': 169,
                                       'flowtool-python-0.7.19': 149,
                                       'flowtool-python-0.7.20': 147,
                                       'flowtool-python-0.7.21': 146,
                                       'flowtool-python-0.7.22': 145,
                                       'flowtool-python-0.7.23': 144,
                                       'flowtool-python-0.7.24': 140,
                                       'flowtool-python-0.7.25': 139,
                                       'flowtool-python-0.7.26': 137,
                                       'flowtool-python-0.7.27': 131,
                                       'flowtool-python-0.7.28': 128,
                                       'flowtool-python-0.7.29': 126,
                                       'flowtool-python-0.7.30': 125,
                                       'flowtool-python-0.7.31': 117,
                                       'flowtool-python-0.7.32': 116,
                                       'flowtool-python-0.7.33': 101,
                                       'flowtool-python-0.7.34': 88,
                                       'flowtool-python-0.7.35': 84,
                                       'flowtool-python-0.7.36': 75,
                                       'flowtool-python-0.7.37': 48,
                                       'flowtool-python-0.7.38': 25,
                                       'flowtool-python-0.7.39': 22,
                                       'flowtool-python-0.7.40': 17,
                                       'flowtool-python-0.7.41': 6,
                                       'flowtool-python-0.7.42': 0},
              'tag_version': {'normalized': '0.7.42',
                              'release': (0, 7, 42),
                              'version': '0.7.42'}},
 'version': '0.7.42'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
