
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e6f75c627fc9492ba58cc06be7c031dfcfb1fcab",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
