profile: private
region: us-east-1
versioning: true
default_alias: test
clean_build: true
configuration:
  name: lamvery
  runtime: python2.7
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: lambda_function.lambda_handler
  description: This is sample lambda function.
  timeout: 10
  memory_size: 128
  # vpc_config:
  #   subnets:
  #   - subnet-cadf2993
  #   security_groups:
  #   - sg-4d095028
