"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': 'e10b9293794336368b981d8f8e0e39d2b868ee22',
              'dirt': '',
              'latest_tag': 'flowtool-git-0.7.11',
              'latest_tag_commit': 'e10b9293794336368b981d8f8e0e39d2b868ee22',
              'latest_tag_version': '0.7.11',
              'prefix': 'flowtool-git-',
              'prefix_tag_distances': {'flowtool-git-0.7.10': 11,
                                       'flowtool-git-0.7.11': 0,
                                       'flowtool-git-0.7.7': 50,
                                       'flowtool-git-0.7.8': 49,
                                       'flowtool-git-0.7.9': 26},
              'tag_version': {'normalized': '0.7.11',
                              'release': (0, 7, 11),
                              'version': '0.7.11'}},
 'version': '0.7.11'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
