"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'fd2f39920f04a8a91fc6543d5ed8ac1a452e5553',
              'dirt': '',
              'latest_tag': 'flowtool-releasing-0.7.17',
              'latest_tag_commit': 'fd2f39920f04a8a91fc6543d5ed8ac1a452e5553',
              'latest_tag_version': '0.7.17',
              'prefix': 'flowtool-releasing-',
              'prefix_tag_distances': {'flowtool-releasing-0.7.16': 126,
                                       'flowtool-releasing-0.7.17': 0},
              'tag_version': {'normalized': '0.7.17',
                              'release': (0, 7, 17),
                              'version': '0.7.17'}},
 'version': '0.7.17'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
