
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0327c9673e51dcc1154ec307de266db17fd5c264",
 "version": "1.0.43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
