"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '77f1b04b1c356d65379d55adf9af2599755fdfbc',
              'dirt': '',
              'latest_tag': 'flowtool-base-0.7.48',
              'latest_tag_commit': '77f1b04b1c356d65379d55adf9af2599755fdfbc',
              'latest_tag_version': '0.7.48',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {'flowtool-base-0.7.47': 29,
                                       'flowtool-base-0.7.48': 0},
              'tag_version': {'normalized': '0.7.48',
                              'release': (0, 7, 48),
                              'version': '0.7.48'}},
 'version': '0.7.48'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
