reference: sequence.fasta

samples: 
    - ERR036019_1.fastq.gz
    - ERR036019_2.fastq.gz

output: ERR036019

bwa_index:
    -a: "is"

# Module load ------------------------------------------------------------------
on_cluster: no
src_module: /etc/profile.d/pasteur_modules.sh
bwa_module: bwa/0.7.5a
samtools_module: samtools/1.2
