
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "178736aae7f87f6660c1ce9a9d403281fbd532c2",
 "version": "0.2.post14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
