"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'afa5349e480f5bd322e4a3cb96cc32dd9bfc5cd9',
              'dirt': '',
              'latest_tag': 'flowtool-versioning-0.7.51',
              'latest_tag_commit': 'afa5349e480f5bd322e4a3cb96cc32dd9bfc5cd9',
              'latest_tag_version': '0.7.51',
              'prefix': 'flowtool-versioning-',
              'prefix_tag_distances': {'flowtool-versioning-0.7.48': 8,
                                       'flowtool-versioning-0.7.49': 6,
                                       'flowtool-versioning-0.7.50': 5,
                                       'flowtool-versioning-0.7.51': 0},
              'tag_version': {'normalized': '0.7.51',
                              'release': (0, 7, 51),
                              'version': '0.7.51'}},
 'version': '0.7.51'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
