"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'tag_version': {'normalized': '0.7.12',
                 'release': (0, 7, 12),
                 'version': '0.7.12'},
 'vcs_info': {'commit': '7ff0de207726dae37cb13b64fa898b3e9943166d',
              'dirt': '',
              'latest_tag': 'flowtool-python-0.7.12',
              'latest_tag_commit': '7ff0de207726dae37cb13b64fa898b3e9943166d',
              'latest_tag_version': '0.7.12',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.11': 5,
                                       'flowtool-python-0.7.12': 0}},
 'version': '0.7.12'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', 'no_version')
