bind:
  address: '0.0.0.0'
  port: 8080
auth:
# HTTP Authentication, could be nothing
  username: ''
  password: ''
proxy:
# Keys and values must match the omega rule
  profile:
    first: 'http://username:password@127.0.0.1:12345' # 'username:password@' could be nothing
    second: 'socks5://127.0.0.1:23456'
    direct: 'direct://'
  virtual:
  # Virtual profile as alias
    speed: "first"
omega_file: 'omega.conf'
ipv6_test:
  host: 'www.yahoo.com'
  port: 443