language: python

dist: trusty

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4

before_script:
  - mkdir mongodb
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.7.tgz -q -O - | tar xz -C mongodb --strip-components=1
  - export PATH=`pwd`/mongodb/bin:$PATH

script:
  # force pytest upgrade to avoid VersionConflict
  - pip install -U pytest
  - python setup.py test
  - pip install -e .
  - mongo --nodb tests/suite.js
