# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microbot', '0008_auto_20160329_0516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handler',
            options={'ordering': ['-priority'], 'verbose_name': 'Handler', 'verbose_name_plural': 'Handlers'},
        ),
        migrations.AddField(
            model_name='handler',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
    ]
