# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microbot', '0011_auto_20160330_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='method',
            field=models.CharField(choices=[(b'Get', 'Get'), (b'Post', 'Post'), (b'Put', 'Put'), (b'Delete', 'Delete'), (b'Patch', 'Patch')], default=b'Get', max_length=128, verbose_name='Method'),
        ),
    ]
