# This file was auto-generated by salt's setup on Thursday, 14 April 2016 @ 15:04:30 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2015, 8, 8, 2, 0, 0, None)
