
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0043ff7ba74fba6c0c609fed9d347d44ea8a17b8",
 "version": "0.4.post15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
