
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.4'
version_full = '85738f4d08c1f9efff8e14c74de76f346b5f3bae'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

