"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '87fa93a89a0c3cd0b05bb6528ce088076d30264f',
              'dirt': '',
              'latest_tag': 'flowtool-base-0.7.49',
              'latest_tag_commit': '87fa93a89a0c3cd0b05bb6528ce088076d30264f',
              'latest_tag_version': '0.7.49',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {'flowtool-base-0.7.47': 32,
                                       'flowtool-base-0.7.48': 3,
                                       'flowtool-base-0.7.49': 0},
              'tag_version': {'normalized': '0.7.49',
                              'release': (0, 7, 49),
                              'version': '0.7.49'}},
 'version': '0.7.49'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
