"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': u'eb667b55db89ca4f49bb0b2289528f3fe40f36ca',
              'dirt': u'',
              'latest_tag': u'flowtool-base-0.7.23',
              'latest_tag_commit': u'eb667b55db89ca4f49bb0b2289528f3fe40f36ca',
              'latest_tag_version': u'0.7.23',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {u'flowtool-base-0.7.12': 53,
                                       u'flowtool-base-0.7.13': 35,
                                       u'flowtool-base-0.7.14': 33,
                                       u'flowtool-base-0.7.15': 32,
                                       u'flowtool-base-0.7.16': 31,
                                       u'flowtool-base-0.7.17': 30,
                                       u'flowtool-base-0.7.18': 28,
                                       u'flowtool-base-0.7.19': 24,
                                       u'flowtool-base-0.7.20': 19,
                                       u'flowtool-base-0.7.21': 18,
                                       u'flowtool-base-0.7.22': 17,
                                       u'flowtool-base-0.7.23': 0},
              'tag_version': {'normalized': '0.7.23',
                              'release': (0, 7, 23),
                              'version': u'0.7.23'}},
 'version': u'0.7.23'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
