
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "83e7561d334d888493daf942017a749b4092f6c8",
 "version": "0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
