"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': 'cad5e7a156b737af265cd9e2cef2d8e85574e1b8',
              'dirt': '',
              'latest_tag': 'flowtool-python-0.7.18',
              'latest_tag_commit': 'cad5e7a156b737af265cd9e2cef2d8e85574e1b8',
              'latest_tag_version': '0.7.18',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.15': 6,
                                       'flowtool-python-0.7.16': 5,
                                       'flowtool-python-0.7.17': 4,
                                       'flowtool-python-0.7.18': 0},
              'tag_version': {'normalized': '0.7.18',
                              'release': (0, 7, 18),
                              'version': '0.7.18'}},
 'version': '0.7.18'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
