"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'bb1d7451e305a908cadaab4ac9d794c36140cd4e',
              'dirt': '',
              'latest_tag': 'flowtool-releasing-0.7.20',
              'latest_tag_commit': 'bb1d7451e305a908cadaab4ac9d794c36140cd4e',
              'latest_tag_version': '0.7.20',
              'prefix': 'flowtool-releasing-',
              'prefix_tag_distances': {'flowtool-releasing-0.7.17': 51,
                                       'flowtool-releasing-0.7.18': 50,
                                       'flowtool-releasing-0.7.19': 45,
                                       'flowtool-releasing-0.7.20': 0},
              'tag_version': {'normalized': '0.7.20',
                              'release': (0, 7, 20),
                              'version': '0.7.20'}},
 'version': '0.7.20'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
