"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '03bbe93f57ea69ba276dc2619f07707690c16c4c',
              'dirt': '',
              'latest_tag': 'flowtool-githooks-0.7.32',
              'latest_tag_commit': '03bbe93f57ea69ba276dc2619f07707690c16c4c',
              'latest_tag_version': '0.7.32',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {'flowtool-githooks-0.7.31': 53,
                                       'flowtool-githooks-0.7.32': 0},
              'tag_version': {'normalized': '0.7.32',
                              'release': (0, 7, 32),
                              'version': '0.7.32'}},
 'version': '0.7.32'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
