"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': u'6ad2ab9fa25f16b901b316a82e6f71554f190c79',
              'dirt': u'',
              'latest_tag': u'flowtool-githooks-0.7.14',
              'latest_tag_commit': u'6ad2ab9fa25f16b901b316a82e6f71554f190c79',
              'latest_tag_version': u'0.7.14',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {u'flowtool-githooks-0.7.13': 23,
                                       u'flowtool-githooks-0.7.14': 0},
              'tag_version': {'normalized': '0.7.14',
                              'release': (0, 7, 14),
                              'version': u'0.7.14'}},
 'version': u'0.7.14'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
