
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.1'
version_full = '2fb4c1b251a26ae927e07ab28cdce58cebc22f54'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

