mongo:
   image: mongo:3.2.3
app:
   build: .
   dockerfile: Dockerfile-app
   environment:
      - VIRTUAL_ENV=/usr/local/
   volumes:
      - .:/baleen
   links:
      - mongo
   ports:
      - 5000:5000
   restart: always