
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "08807cff6d7f9af3b327c8c413684744040b8301",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
