
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9e67b250ebdae5dc60d62ccfd1a6f13086c8fe3e",
 "version": "v0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
