
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7c2ae878eb0bd4fe98d3b697dc0474543cd92858",
 "version": "0.4.post13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
