
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.3.2'
version_full = '09ad04de5526960f9a67eea387f05fd1ec4e1292'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

