"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'fcefa27ac72c8a24167623a6080438ed86acf04f',
              'dirt': '',
              'latest_tag': 'flowtool-python-0.7.36',
              'latest_tag_commit': 'fcefa27ac72c8a24167623a6080438ed86acf04f',
              'latest_tag_version': '0.7.36',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.11': 201,
                                       'flowtool-python-0.7.12': 196,
                                       'flowtool-python-0.7.13': 194,
                                       'flowtool-python-0.7.14': 103,
                                       'flowtool-python-0.7.15': 100,
                                       'flowtool-python-0.7.16': 99,
                                       'flowtool-python-0.7.17': 98,
                                       'flowtool-python-0.7.18': 94,
                                       'flowtool-python-0.7.19': 74,
                                       'flowtool-python-0.7.20': 72,
                                       'flowtool-python-0.7.21': 71,
                                       'flowtool-python-0.7.22': 70,
                                       'flowtool-python-0.7.23': 69,
                                       'flowtool-python-0.7.24': 65,
                                       'flowtool-python-0.7.25': 64,
                                       'flowtool-python-0.7.26': 62,
                                       'flowtool-python-0.7.27': 56,
                                       'flowtool-python-0.7.28': 53,
                                       'flowtool-python-0.7.29': 51,
                                       'flowtool-python-0.7.30': 50,
                                       'flowtool-python-0.7.31': 42,
                                       'flowtool-python-0.7.32': 41,
                                       'flowtool-python-0.7.33': 26,
                                       'flowtool-python-0.7.34': 13,
                                       'flowtool-python-0.7.35': 9,
                                       'flowtool-python-0.7.36': 0},
              'tag_version': {'normalized': '0.7.36',
                              'release': (0, 7, 36),
                              'version': '0.7.36'}},
 'version': '0.7.36'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
