"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '0edde51776998bde661350fa86c6756d53f218a3',
              'dirt': '',
              'latest_tag': 'flowtool-githooks-0.7.22',
              'latest_tag_commit': '0edde51776998bde661350fa86c6756d53f218a3',
              'latest_tag_version': '0.7.22',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {'flowtool-githooks-0.7.13': 118,
                                       'flowtool-githooks-0.7.14': 95,
                                       'flowtool-githooks-0.7.15': 49,
                                       'flowtool-githooks-0.7.16': 41,
                                       'flowtool-githooks-0.7.17': 40,
                                       'flowtool-githooks-0.7.18': 39,
                                       'flowtool-githooks-0.7.19': 36,
                                       'flowtool-githooks-0.7.20': 15,
                                       'flowtool-githooks-0.7.21': 2,
                                       'flowtool-githooks-0.7.22': 0,
                                       'flowtool-githooks-demo-0.7.4': 89,
                                       'flowtool-githooks-demo-0.7.5': 88},
              'tag_version': {'normalized': '0.7.22',
                              'release': (0, 7, 22),
                              'version': '0.7.22'}},
 'version': '0.7.22'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
