"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '7959a7343bfa2c6255f3dd17d532b9b9fed62cf6',
              'dirt': '',
              'latest_tag': 'data-pypes-0.1.7',
              'latest_tag_commit': '7959a7343bfa2c6255f3dd17d532b9b9fed62cf6',
              'latest_tag_version': '0.1.7',
              'prefix': 'data-pypes-',
              'prefix_tag_distances': {'data-pypes-0.1.1': 24,
                                       'data-pypes-0.1.2': 22,
                                       'data-pypes-0.1.3': 20,
                                       'data-pypes-0.1.4': 15,
                                       'data-pypes-0.1.5': 9,
                                       'data-pypes-0.1.6': 7,
                                       'data-pypes-0.1.7': 0},
              'tag_version': {'normalized': '0.1.7',
                              'release': (0, 1, 7),
                              'version': '0.1.7'}},
 'version': '0.1.7'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
