"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '81053ca5acc0618264d6812fc75da229aa412d35',
              'dirt': '',
              'latest_tag': 'flowtool-githooks-0.7.27',
              'latest_tag_commit': '81053ca5acc0618264d6812fc75da229aa412d35',
              'latest_tag_version': '0.7.27',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {'flowtool-githooks-0.7.13': 170,
                                       'flowtool-githooks-0.7.14': 147,
                                       'flowtool-githooks-0.7.15': 101,
                                       'flowtool-githooks-0.7.16': 93,
                                       'flowtool-githooks-0.7.17': 92,
                                       'flowtool-githooks-0.7.18': 91,
                                       'flowtool-githooks-0.7.19': 88,
                                       'flowtool-githooks-0.7.20': 67,
                                       'flowtool-githooks-0.7.21': 54,
                                       'flowtool-githooks-0.7.22': 52,
                                       'flowtool-githooks-0.7.23': 48,
                                       'flowtool-githooks-0.7.24': 46,
                                       'flowtool-githooks-0.7.25': 43,
                                       'flowtool-githooks-0.7.26': 16,
                                       'flowtool-githooks-0.7.27': 0},
              'tag_version': {'normalized': '0.7.27',
                              'release': (0, 7, 27),
                              'version': '0.7.27'}},
 'version': '0.7.27'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
