type: microplate

rows: 6
cols: 4
a1_x: 13.5
a1_y: 17.5
spacing: 19.3
diameter: 15.62

height: 16.2
well_depth: 16.2

volume: 3400 # Maximum volume
min_vol: 380 # Minimum working volume
max_vol: 570 # Maximum working volume