
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1f98566e2cda7af3048001fb99d53f1a92f150d7",
 "version": "1.0.0.post.dev135"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
