
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.19'
version_full = '9566e2893846da8ed0c7a633892f55d346b52d86'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

