"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '3e7483d8f238b0f3d849fe684e13ef071ac0b632',
              'dirt': '',
              'latest_tag': 'flowtool-base-0.7.36',
              'latest_tag_commit': '3e7483d8f238b0f3d849fe684e13ef071ac0b632',
              'latest_tag_version': '0.7.36',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {'flowtool-base-0.7.12': 118,
                                       'flowtool-base-0.7.13': 100,
                                       'flowtool-base-0.7.14': 98,
                                       'flowtool-base-0.7.15': 97,
                                       'flowtool-base-0.7.16': 96,
                                       'flowtool-base-0.7.17': 95,
                                       'flowtool-base-0.7.18': 93,
                                       'flowtool-base-0.7.19': 89,
                                       'flowtool-base-0.7.20': 84,
                                       'flowtool-base-0.7.21': 83,
                                       'flowtool-base-0.7.22': 82,
                                       'flowtool-base-0.7.23': 65,
                                       'flowtool-base-0.7.24': 61,
                                       'flowtool-base-0.7.25': 60,
                                       'flowtool-base-0.7.26': 59,
                                       'flowtool-base-0.7.27': 58,
                                       'flowtool-base-0.7.28': 57,
                                       'flowtool-base-0.7.29': 51,
                                       'flowtool-base-0.7.30': 50,
                                       'flowtool-base-0.7.31': 45,
                                       'flowtool-base-0.7.32': 40,
                                       'flowtool-base-0.7.33': 38,
                                       'flowtool-base-0.7.34': 35,
                                       'flowtool-base-0.7.35': 7,
                                       'flowtool-base-0.7.36': 0},
              'tag_version': {'normalized': '0.7.36',
                              'release': (0, 7, 36),
                              'version': '0.7.36'}},
 'version': '0.7.36'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
