"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'f88e7c93476a4a30fb70459c5a62495402b3a7a2',
              'dirt': '',
              'latest_tag': 'flowtool-githooks-0.7.38',
              'latest_tag_commit': 'f88e7c93476a4a30fb70459c5a62495402b3a7a2',
              'latest_tag_version': '0.7.38',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {'flowtool-githooks-0.7.35': 21,
                                       'flowtool-githooks-0.7.36': 10,
                                       'flowtool-githooks-0.7.37': 8,
                                       'flowtool-githooks-0.7.38': 0},
              'tag_version': {'normalized': '0.7.38',
                              'release': (0, 7, 38),
                              'version': '0.7.38'}},
 'version': '0.7.38'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
