"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '8557c509a41114ac7d20d08ace680882d30978d4',
              'dirt': '',
              'latest_tag': 'flowtool-githooks-0.7.25',
              'latest_tag_commit': '8557c509a41114ac7d20d08ace680882d30978d4',
              'latest_tag_version': '0.7.25',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {'flowtool-githooks-0.7.13': 127,
                                       'flowtool-githooks-0.7.14': 104,
                                       'flowtool-githooks-0.7.15': 58,
                                       'flowtool-githooks-0.7.16': 50,
                                       'flowtool-githooks-0.7.17': 49,
                                       'flowtool-githooks-0.7.18': 48,
                                       'flowtool-githooks-0.7.19': 45,
                                       'flowtool-githooks-0.7.20': 24,
                                       'flowtool-githooks-0.7.21': 11,
                                       'flowtool-githooks-0.7.22': 9,
                                       'flowtool-githooks-0.7.23': 5,
                                       'flowtool-githooks-0.7.24': 3,
                                       'flowtool-githooks-0.7.25': 0,
                                       'flowtool-githooks-demo-0.7.4': 98,
                                       'flowtool-githooks-demo-0.7.5': 97},
              'tag_version': {'normalized': '0.7.25',
                              'release': (0, 7, 25),
                              'version': '0.7.25'}},
 'version': '0.7.25'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
