"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': u'0f02b834eab8bb0542d15945f66704e138c8e6c7',
              'dirt': u'',
              'latest_tag': u'flowtool-base-0.7.22',
              'latest_tag_commit': u'0f02b834eab8bb0542d15945f66704e138c8e6c7',
              'latest_tag_version': u'0.7.22',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {u'flowtool-base-0.7.12': 36,
                                       u'flowtool-base-0.7.13': 18,
                                       u'flowtool-base-0.7.14': 16,
                                       u'flowtool-base-0.7.15': 15,
                                       u'flowtool-base-0.7.16': 14,
                                       u'flowtool-base-0.7.17': 13,
                                       u'flowtool-base-0.7.18': 11,
                                       u'flowtool-base-0.7.19': 7,
                                       u'flowtool-base-0.7.20': 2,
                                       u'flowtool-base-0.7.21': 1,
                                       u'flowtool-base-0.7.22': 0},
              'tag_version': {'normalized': '0.7.22',
                              'release': (0, 7, 22),
                              'version': u'0.7.22'}},
 'version': u'0.7.22'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
