#!/usr/bin/env python
# -*- coding: utf-8 -*-

new_positions = [
    u"CONS.OTR.EXT",
    u"VPRSCOMAUCNT",
    u"SEC.COM.CONS",
    u"0APODERADO",
    u"0DM.CONJUNTO",
    u"ADJ.GERENCIA",
    u"ADM. MANCO",
    u"ADM. MANCO.",
    u"ADM. SOLIDA.",
    u"ADM. UNICO 2",
    u"ADM. UNICO.",
    u"ADM.ADJUNTO",
    u"ADM.PROV.SOL",
    u"ADM.SUP.MAN.",
    u"ADMIN.1º",
    u"ADMIN.HECH.",
    u"ADMIN.JUDIC",
    u"ADMIN.UNICO.",
    u"ADMINPROVI",
    u"ADMPROVSOLEF",
    u"AG.REV.TIT.",
    u"APOD.CONJUN.",
    u"APOD.GERENTE",
    u"APOD.MANC",
    u"APOD.SOLID",
    u"APOD.SUCURSA",
    u"ARCHIV.JTA.D",
    u"ASESOR JURI.",
    u"ASESOR REG",
    u"AUD.",
    u"AUD.C.C.CONJ",
    u"AUD.MANC",
    u"AUD.SUP.GRUP",
    u"AUD.SUPL.C.C",
    u"AUD.TIT.GRUP",
    u"AUDIT.",
    u"AUDIT.CC.SUP",
    u"AUDIT.CC.TIT",
    u"AUDITOR CONS",
    u"AUDITOR GRUP",
    u"AUDITOR TIT.",
    u"AUX.ADM.CONC",
    u"CAPITAL",
    u"CDS.CONS.LIQ",
    u"CGM.A.G",
    u"CO.C.RIESGOS",
    u"COM.CONT.SEG",
    u"COM.CONTROL",
    u"COM.CTRL.Y.S",
    u"COM.LIQ",
    u"COM.NOMB.",
    u"COMIS.AUDITO",
    u"COMIS.CONTRO",
    u"COMIS.OPERAC",
    u"COMS.ACREED.",
    u"COMS.DEL.INV",
    u"COMS.SEGUIM.",
    u"COMS.VIGILAN",
    u"CON.DEL.COM.",
    u"CON.DEL.MANC",
    u"CON.DEL.SUP.",
    u"CON.IND.COOR",
    u"CON.INDEPEND",
    u"CON.INTERIN.",
    u"CONS. HONOR.",
    u"CONS. IDPTE.",
    u"CONS.",
    u"CONS.COOR.CA",
    u"CONS.DEL.C.R",
    u"CONS.DEL.COM",
    u"CONS.DEL.JUN",
    u"CONS.DOMINIC",
    u"CONS.EJECUTI",
    u"CONS.EXT.DOM",
    u"CONS.EXTERNO",
    u"CONS.HONORA.",
    u"CONS.INDEPEN",
    u"CONS.INTERIN",
    u"CONS.SUPLENT",
    u"CONSEJ.COORD",
    u"CONSJ.DOMINI",
    u"CONSJ.SUPL.",
    u"CONTAD.JTA.D",
    u"CONTROLLER",
    u"COPRE.COMEJ",
    u"COPRE.CONADM",
    u"D. COMERCIAL",
    u"D.G.CONS.REC",
    u"DEFENS.PART.",
    u"DELEG.",
    u"DELEG.GNERAL",
    u"DEP.COM.CTR.",
    u"DIR.ADM.",
    u"DIR.GEN.SPL",
    u"DIR.GRAL.",
    u"DIR.PLANIF.",
    u"DM.UNICO 2",
    u"DTOR.ADMINIS",
    u"DTOR.COMERC.",
    u"DTOR.DEPART.",
    u"DTOR.ECON.FI",
    u"DTOR.EJECUT.",
    u"DTOR.EXPLOTA",
    u"DTOR.FABRICA",
    u"DTOR.FINANC.",
    u"DTOR.GE.CO.E",
    u"DTOR.GEN.EJC",
    u"DTOR.GEN.FIN",
    u"DTOR.GRAL.AD",
    u"DTOR.MARKET.",
    u"DTOR.OPERCIO",
    u"DTOR.REC.HUM",
    u"EEADMONSICAV",
    u"EEREPSTSICAV",
    u"EMPL.AG.RUR.",
    u"ENT.COGESTOR",
    u"ENT.DEPOSITA",
    u"ENT.GESTORA",
    u"ENT.TASACIÓN",
    u"ENTI.PROMOT.",
    u"EXP.IND.",
    u"FUNDADOR",
    u"GER.ADMIN.",
    u"GER.COMER.",
    u"GER.EJE.",
    u"GERENTE SMCP",
    u"GERENTE SUC.",
    u"GERENTE.ADJT",
    u"GESTOR",
    u"INTER.JTA.D",
    u"INTER.SUP",
    u"INTERV.SOLID",
    u"LETRD.ASESOR",
    u"LIQ.JUDICIAL",
    u"LIQ.SUP.",
    u"LIQUID.DELEG",
    u"LIQUID.SUPL.",
    u"M.C.COM.PERM",
    u"M.CO.DE.IN",
    u"M.COM. ASESO",
    u"M.COM.CONSU.",
    u"M.COM.INV",
    u"M.COM.RETR.",
    u"M.COM.SEG.FO",
    u"M.COMI.PERMA",
    u"M.COMIT.INV",
    u"M.COMIT.REC.",
    u"M.COMS.E.O.S",
    u"M.COMS.NOMBR",
    u"M.SUPL.C.LIQ",
    u"M.SUPL.COM.R",
    u"MANCOM.",
    u"MANDATARIO",
    u"MBRO.C.RESPO",
    u"MBRO.CJO.ASE",
    u"MBRO.CMS.INV",
    u"MBRO.COM.ASE",
    u"MBRO.COM.CRT",
    u"MBRO.COM.CYA",
    u"MBRO.COM.DIR",
    u"MBRO.COM.GER",
    u"MBRO.COM.INV",
    u"MBRO.COM.RET",
    u"MBRO.COM.RIE",
    u"MBRO.COMISIO",
    u"MBRO.CON.DIR",
    u"MBRO.CONS.GO",
    u"MBRO.S.O.CTR",
    u"MECONORE",
    u"MED.CONCUSAL",
    u"MEDIAD.CONCU",
    u"MI.O.C.C",
    u"MICOAUDI",
    u"MICOEMPA",
    u"MIE.CM.PGCRI",
    u"MIE.COM.ANR",
    u"MIE.COM.AR",
    u"MIE.COM.EJCR",
    u"MIE.COM.GOB.",
    u"MIE.COM.REP.",
    u"MIECONSOCGER",
    u"MIEM.C.D.C.A",
    u"MIEM.C.PRO",
    u"MIEM.CO.REC",
    u"MIEM.CO.REC.",
    u"MIEM.COM.ACR",
    u"MIEM.COM.CON",
    u"MIEM.COM.DEL",
    u"MIEM.COM.FIN",
    u"MIEM.COM.NOM",
    u"MIEM.COM.O.S",
    u"MIEM.COM.REC",
    u"MIEM.COM.RI.",
    u"MIEM.COM.RIE",
    u"MIEM.COM.SEG",
    u"MIEM.CON.DIR",
    u"MIEM.CTE.CON",
    u"MIEM.J.ADM.",
    u"MIEMB.CTE.CF",
    u"MIEMCOMIGEST",
    u"MIEMCOMINDP",
    u"MIEMCOMMIX",
    u"MIEMCOMOPVIN",
    u"MIEMCONSASE",
    u"MMBR.COM.LIQ",
    u"MRO.C.SEGURI",
    u"MRO.COMS.DEL",
    u"MRO.COMS.DIR",
    u"MRO.COMS.EST",
    u"MRO.COMS.LIQ",
    u"MRO.COMS.O.S",
    u"MRO.COMS.PER",
    u"MRO.T.COM.RE",
    u"OTORGANTE",
    u"OTROS",
    u"P.CO.DE.IN",
    u"P.COM.EJEC.",
    u"P.COMS.E.O.S",
    u"PATRONO",
    u"PDTE.",
    u"PDTE.COM.CYA",
    u"PR.C.INV",
    u"PR.COM,CONTR",
    u"PR.COM.EJECU",
    u"PR.COM.RI.",
    u"PR.COMS.NOMB",
    u"PR.S.JTA.D",
    u"PRE.1JTA.D",
    u"PRE.C.RIESGO",
    u"PRE.C.SEGURI",
    u"PRE.CM.PGCRI",
    u"PRE.CO.O.S",
    u"PRE.COM.ANR",
    u"PRE.COM.AR",
    u"PRE.COM.AUD.",
    u"PRE.COM.GER",
    u"PRE.COM.GERE",
    u"PRE.COM.GOB",
    u"PRE.COM.GOB.",
    u"PRE.COM.IN",
    u"PRE.COM.PERM",
    u"PRE.COM.REP.",
    u"PRE.COMS.AUD",
    u"PRE.COMS.D.I",
    u"PRE.COMS.DEL",
    u"PRE.COMS.EST",
    u"PRE.COMS.LIQ",
    u"PRE.COMS.O.S",
    u"PRE.COMS.PER",
    u"PRE.CON.GOB.",
    u"PRE.CONS.R",
    u"PRE.JTA.DI",
    u"PRE.JTA.RECT",
    u"PRECOEMPA",
    u"PRECOMNOMRE",
    u"PRECONSOCGER",
    u"PRES. SUP",
    u"PRES.ASAM.SO",
    u"PRES.C.D.C.A",
    u"PRES.C.PRO",
    u"PRES.CMS.INV",
    u"PRES.COM.CON",
    u"PRES.COM.CRT",
    u"PRES.COM.CTO",
    u"PRES.COM.DIR",
    u"PRES.COM.EIC",
    u"PRES.COM.EJE",
    u"PRES.COM.INV",
    u"PRES.COM.NOM",
    u"PRES.COM.O.S",
    u"PRES.COM.REC",
    u"PRES.COM.RET",
    u"PRES.COM.RI",
    u"PRES.COM.RIE",
    u"PRES.COM.SEG",
    u"PRES.CON.DIR",
    u"PRES.CON.REC",
    u"PRES.CTE.CON",
    u"PRES.J.ADM.",
    u"PRES.JTA.ADM",
    u"PRES.NOMB.RE",
    u"PRES.SOCIED.",
    u"PRESASAMBL",
    u"PRESCOMAUCNT",
    u"PRESCOMIGEST",
    u"PRESCOMOPVIN",
    u"PRESID.JUNTA",
    u"PRESID.OPERA",
    u"PTE ESTRATEG",
    u"PTE.COM.EJCR",
    u"PTE.COM.INV",
    u"PTE.COM.RET.",
    u"PTE.COMI.RES",
    u"R.L.C.PERM.",
    u"REP.SEPBLAC",
    u"REPR. SUPLT.",
    u"REPR.PERMAN",
    u"REPRESENT.",
    u"REPRESENTAN.",
    u"RPTE. SUC.",
    u"S.N.C.C.D.I.",
    u"S.NO CONS.GO",
    u"S.NO.C.CO.EJ",
    u"SCR. C. AUD.",
    u"SCR.COM.CONT",
    u"SCR.COM.EJEC",
    u"SCR.NO.COM.E",
    u"SCRNO.CONS",
    u"SCT ESTRATEG",
    u"SDTOR.GRAL.A",
    u"SEC.A.G.P.V",
    u"SEC.ACC.ACTA",
    u"SEC.ACTAS",
    u"SEC.C.D.C.A",
    u"SEC.C.PRO",
    u"SEC.C.SEGURI",
    u"SEC.CM.PGCRI",
    u"SEC.COM.A.YC",
    u"SEC.COM.ANR",
    u"SEC.COM.AUD",
    u"SEC.COM.AUD.",
    u"SEC.COM.DEL",
    u"SEC.COM.EJCR",
    u"SEC.COM.EJEC",
    u"SEC.COM.GER",
    u"SEC.COM.GOB.",
    u"SEC.COM.N.R.",
    u"SEC.COM.PERM",
    u"SEC.COM.REC.",
    u"SEC.COM.REP.",
    u"SEC.COM.RET.",
    u"SEC.COMS.AUD",
    u"SEC.COMS.C",
    u"SEC.COMS.DEL",
    u"SEC.COMS.EST",
    u"SEC.COMS.LIQ",
    u"SEC.COMS.O.S",
    u"SEC.CONS.GOB",
    u"SEC.G.C.A",
    u"SEC.JTA.DI",
    u"SEC.JTA.RECT",
    u"SEC.NO.C.O.S",
    u"SEC.SUPLENTE",
    u"SECCOMAUDIT.",
    u"SECCONSOCGER",
    u"SECOAUDI",
    u"SECOEMPA",
    u"SECONORE",
    u"SECORIES",
    u"SECR.ADJUNTO",
    u"SECR.ASAM.SO",
    u"SECR.C.RET",
    u"SECR.CO.GERE",
    u"SECR.COM.CON",
    u"SECR.COM.CTO",
    u"SECR.COM.CYA",
    u"SECR.COM.DEL",
    u"SECR.COM.EIC",
    u"SECR.COM.INV",
    u"SECR.COM.NOM",
    u"SECR.COM.O.S",
    u"SECR.COM.RET",
    u"SECR.COM.RI.",
    u"SECR.COM.RIE",
    u"SECR.CON.DIR",
    u"SECR.CON.REC",
    u"SECR.CTE.CON",
    u"SECR.CTE.NYR",
    u"SECR.GENERAL",
    u"SECR.GRAL.AD",
    u"SECR.J.ADM.",
    u"SECR.JUNTA",
    u"SECR.NO.MIEN",
    u"SECR.SOCIED.",
    u"SECR.SUP.NOC",
    u"SECR.SUPL.",
    u"SECR.TECNICO",
    u"SECR2.COM.EJ",
    u"SECRCOMAUCNT",
    u"SECRCOMAUCUM",
    u"SECRCOMIGEST",
    u"SECRCOMOPVIN",
    u"SECRET.GRAL.",
    u"SECSU.CONADM",
    u"SINDICO",
    u"SOCCOMTINTEG",
    u"SOCGESTMANC",
    u"SOCIO COLECT",
    u"SOCIO HONOR",
    u"SOLID.",
    u"SUB.GENERAL",
    u"SUBDIREC",
    u"SUBDIRECTOR",
    u"SUBDTOR.GNRL",
    u"SUP.",
    u"SUP.COM.EJ.C",
    u"SUPL.CJO.ADM",
    u"SUPL.COM.CON",
    u"SUPL.COM.REC",
    u"SUPL.COMS.CT",
    u"SUPL.J.ADM.",
    u"SUPL.J.DIREC",
    u"SUPL1.CON.RE",
    u"SUPL2.CON.RE",
    u"SUPL3.CON.RE",
    u"SUPL4.CON.RE",
    u"SUPL5.CON.RE",
    u"SUPLE.CON.RE",
    u"SUPLEN",
    u"SUPLENTE 1",
    u"SUPLENTE 2",
    u"SUPLT.",
    u"SÍNDICO",
    u"TES.COM.EJ.C",
    u"TESO.J.ADM.",
    u"TESOR.JTA.DI",
    u"TESR.CON.REC",
    u"V-CTA.JTA.DI",
    u"V-P.1.COM.EJ",
    u"V-P.1.COMS.E",
    u"V-P.2.COM.EJ",
    u"V-P.2.COMS.E",
    u"V-P2.COM.CTO",
    u"V-PR.S.JTA.D",
    u"V-PR1.CONS.R",
    u"V-PR2.CONS.R",
    u"V-PRE.1.CO.D",
    u"V-PRE.1JTA.D",
    u"V-PRE.2.CO.D",
    u"V-PRE.2JTA.D",
    u"V-PRE.CO.O.S",
    u"V-PRE.COM.IN",
    u"V-PRE.COM.RI",
    u"V-PRE.COMS.C",
    u"V-PRE.COMS.D",
    u"V-PRE.COMS.L",
    u"V-PRE.CON.DI",
    u"V-PRE.CON.GO",
    u"V-PRE.EJ.C.A",
    u"V-PRE.EJECUT",
    u"V-PRE.JTA.DI",
    u"V-PRE.JUNTA",
    u"V-PRES.HONOR",
    u"V-S1.COM.CTO",
    u"V-S2.COM.CTO",
    u"V-SE.S.JTA.D",
    u"V-SEC.2.JT.D",
    u"V-SEC.C.RECT",
    u"V-SEC.COM.IN",
    u"V-SEC.COMS.C",
    u"V-SEC.COMS.D",
    u"V-SEC.COMS.L",
    u"V-SEC.NO.C.1",
    u"V-SEC.NO.C.2",
    u"V-SECR.SOCIE",
    u"V-TESR.JTA.D",
    u"V.TES.",
    u"VCS.CONS.REC",
    u"VCSEC 2 NO C",
    u"VCSEC. C.A.",
    u"VCSEC. C.E.",
    u"VICE.DEPO.",
    u"VICECOMDEL",
    u"VICECONT.",
    u"VICECONTA.J.",
    u"VICEDIR",
    u"VICEDIRECTOR",
    u"VICEP.C.PERM",
    u"VICEPR.3",
    u"VICEPR.4",
    u"VICEPRE.COM.",
    u"VICEPRESI.1º",
    u"VICEPRESI.2º",
    u"VICEPRESID.5",
    u"VICESEC.C.DL",
    u"VICESECRET.1",
    u"VICESECRET.2",
    u"VICESECRET.3",
    u"VICETES.",
    u"VICPRE.J.REC",
    u"VICPRES C.E.",
    u"VICPRES.COM.",
    u"VICPRES.HONO",
    u"VICSEC C.E.",
    u"VICSEC C.L.",
    u"VICSEC. COM.",
    u"VICSEC.C.RET",
    u"VICSEC.CTE.N",
    u"VICSECR.J.R.",
    u"VO.E.P.JT.DI",
    u"VOC.1",
    u"VOC.2",
    u"VOC.3",
    u"VOC.4",
    u"VOC.5",
    u"VOC.COMS.EJ.",
    u"VOC.CON.DIR.",
    u"VOC.CON.GOB.",
    u"VOC.S.JTA.DI",
    u"VOC1.CON.REC",
    u"VOC10 JTA.DI",
    u"VOC10.CON.RE",
    u"VOC2.CON.REC",
    u"VOC2.JTA.DIR",
    u"VOC3.CON.REC",
    u"VOC4.CON.REC",
    u"VOC5.CON.REC",
    u"VOC6.CON.REC",
    u"VOC7.CON.REC",
    u"VOC7.JTA.DIR",
    u"VOC8.CON.REC",
    u"VOC8.JTA.DIR",
    u"VOC9 JTA.DIR",
    u"VOC9.CON.REC",
    u"VOCAL 10",
    u"VOCAL 11",
    u"VOCAL 12",
    u"VOCAL 3",
    u"VOCAL 4",
    u"VOCAL 5",
    u"VOCAL 6",
    u"VOCAL 7",
    u"VOCAL 8",
    u"VOCAL 9",
    u"VOCAL C.RECT",
    u"VOCAL JT.REC",
    u"VOCAL JUNTA",
    u"VOCAL SUPLEN",
    u"VOCAL",
    u"VOCAL.CUARTO",
    u"VOCAL.QUINTO",
    u"VOSU.COM.O.S",
    u"VOTI.COM.NOM",
    u"VOTI.COM.O.S",
    u"VP. AS. GRAL",
    u"VP.AG",
    u"VP.COM.AYR",
    u"VP.COM.RI.",
    u"VP1COM.E.O.S",
    u"VP2.COM.RI.",
    u"VPR.COM.EJEC",
    u"VPR.CONS.LIQ",
    u"VPR2.COM.EJ.",
    u"VPR3.COM.EJ.",
    u"VPRE.A.G.P.V",
    u"VPRE.C.D.C.A",
    u"VPRE.C.PRO",
    u"VPRE.COM.DE",
    u"VPRE.COM.O.S",
    u"VPRE.CON.DIR",
    u"VPRE.J.ADM.",
    u"VPRE.PRES.CO",
    u"VPRECOMILIQU",
    u"VPRES.COM.AU",
    u"VPRES.COM.IN",
    u"VPRT.CM.PERM",
    u"VPTE C.EJ.CR",
    u"VS.N.C.C.A.C",
    u"VS.N.C.C.D.I",
    u"VS.N/C.C.N.R",
    u"VS.NO CON.CE",
    u"VSE.C.SEGURI",
    u"VSEC C.EJ.CR",
    u"VSEC.COM.EJE",
    u"VSEC.COM.O.S",
    u"VSEC.COM.REC",
    u"VSEC.J.G.P.V",
    u"VSEC2.COM.RI",
    u"VSECCOMLIQ",
    u"VSECR.COM.AU",
    u"VSECR.COM.IN",
    u"VSECR1.NC",
    u"VSECR2.NC",
    u"VSECR3.NC",
    u"VTE.COM.DIR.",
]

new_dict = dict([(i, i) for i in new_positions])

assert len(new_dict) == len(new_positions)

POSITION = {
    u"ADM. GERENTE": u"ADM. GERENTE",
    u"ADM. MANCOM.": u"ADM. MANCOM.",
    u"ADM. SOLID.": u"ADM. SOLID.",
    u"ADM. UNICO": u"ADM. UNICO",
    u"ADM.CONCUR": u"ADM.CONCUR",
    u"ADM.CONCURS.": u"ADM.CONCURS.",
    u"ADM.CONJUNTO": u"ADM.CONJUNTO",
    u"ADM.JUDICIAL": u"ADM.JUDICIAL",
    u"ADM.MAN.SUPL": u"ADM.MAN.SUPL",
    u"ADM.SOL.SUPL": u"ADM.SOL.SUPL",
    u"ADM.SOLIDAR.": u"ADM.SOLIDAR.",
    u"ADM.SUPL.": u"ADM.SUPL.",
    u"ADM.SUPLENTE": u"ADM.SUPLENTE",
    u"ADM.UNICO": u"ADM.UNICO",
    u"ADMIN.CONC": u"ADMIN.CONC",
    u"ADMIN.MANC": u"ADMIN.MANC",
    u"ADMIN.SOLID": u"ADMIN.SOLID",
    u"ADMIN.UNICO": u"ADMIN.UNICO",
    u"ADMINISTR.": u"ADMINISTR.",
    u"ADMINISTRAD": u"ADMINISTRAD",
    u"APO.D.GRAL.": u"APO.D.GRAL.",
    u"APO.MAN.SOLI": u"APOD. MANCOM./SOLID.",
    u"APO.MANC.": u"APOD. MANCOM.",
    u"APO.SOL.": u"APOD. SOLID.",
    u"APOD.D.GRAL.": u"APOD.D.GRAL.",
    u"APOD.MANCOMU": u"APOD.MANCOMU",
    u"APOD.SOL/MAN": u"APOD.SOL/MAN",
    u"APODERAD.SOL": u"APODERAD.SOL",
    u"APODERADO": u"APODERADO",
    u"ASESOR": u"ASESOR",
    u"AUD.C.CON.": u"AUD.C.CON.",
    u"AUD.SU.C.CON": u"AUD.SU.C.CON",
    u"AUD.SUPL.": u"AUD.SUPL.",
    u"AUD.SUPL.CC": u"AUD.SUPL.CC",
    u"AUDIT.CONJUN": u"AUDIT.CONJUN",
    u"AUDIT.CUENT.": u"AUDIT.CUENT.",
    u"AUDITOR SUP.": u"AUDITOR SUP.",
    u"AUDITOR TITU": u"AUDITOR TITU",
    u"AUDITOR": u"AUDITOR",
    u"AUDT.CTS.CON": u"AUDT.CTS.CON",
    u"C.CTR=E.PROM": u"C.CTR=E.PROM",
    u"CENSOR CUENT": u"CENSOR CUENT",
    u"CO.DE.MA.SO": u"CO.DE.MA.SO",
    u"COM ESTRATEG": u"COM ESTRATEG",
    u"COM. AUDIT.": u"COM. AUDIT.",
    u"COM.AUD.CTRL": u"COM.AUD.CTRL",
    u"COM.EJECUTIV": u"COM.EJECUTIV",
    u"COM.GERENCIA": u"COM.GERENCIA",
    u"COMISAR.SI.O": u"COMISAR.SI.O",
    u"COMISARIO": u"COMISARIO",
    u"COMISINOBLI": u"COMISINOBLI",
    u"COMISR.SUP.S": u"COMISR.SUP.S",
    u"CON.DEL.SOLI": u"CON.DEL.SOLI",
    u"CON.DELEGADO": u"CON.DELEGADO",
    u"CON.IND.": u"CON.IND.",
    u"CONS. DELEG.": u"CONS. DELEG.",
    u"CONS.DEL.M/S": u"CONS.DEL.M/S",
    u"CONS.DEL.MAN": u"CONS.DEL.MAN",
    u"CONS.DEL.SOL": u"CONS.DEL.SOL",
    u"CONS.DELEGAD": u"CONS.DELEGAD",
    u"CONS.RECTOR": u"CONS.RECTOR",
    u"CONSEJERO": u"CONSEJERO",
    u"CONSEJSUPLEN": u"CONSEJSUPLEN",
    u"CONSJ. SUPL.": u"CONSJ. SUPL.",
    u"CONT.J.DIR.": u"CONT.J.DIR.",
    u"CONTADOR": u"CONTADOR",
    u"COPRESIDENTE": u"COPRESIDENTE",
    u"D. GERENTE": u"D. GERENTE",
    u"DEF PARTICIP": u"DEF PARTICIP",
    u"DEF.PART.": u"DEF.PART.",
    u"DEF.PARTICIP": u"DEF.PARTICIP",
    u"DELEGADO": u"DELEGADO",
    u"DEPOSITARIO": u"DEPOSITARIO",
    u"DIR. GENERAL": u"DIR. GENERAL",
    u"DIR. TÉCNICO": u"DIR. TÉCNICO",
    u"DIR.GRAL.ADJ": u"DIR.GRAL.ADJ",
    u"DIRECTOR GEN": u"DIRECTOR GEN",
    u"DIRECTOR": u"DIRECTOR",
    u"DTOR.GEN.ADJ": u"DTOR.GEN.ADJ",
    u"DTOR.GENERAL": u"DTOR.GENERAL",
    u"DTOR.GERENTE": u"DTOR.GERENTE",
    u"DTOR.SUCURS.": u"DTOR.SUCURS.",
    u"DTOR.TECNICO": u"DTOR.TECNICO",
    u"ENT. GESTORA": u"ENT. GESTORA",
    u"ENT.DEPOSIT.": u"ENT.DEPOSIT.",
    u"ENT.ENC.GEST": u"ENT.ENC.GEST",
    u"ENT.REG.CONT": u"ENT.REG.CONT",
    u"ENTD.PROMO.": u"ENTD.PROMO.",
    u"ENTI.GESTORA": u"ENTI.GESTORA",
    u"ENTIDDEPOSIT": u"ENTIDDEPOSIT",
    u"GER.COM.GER": u"GER.COM.GER",
    u"GERENTE UNI.": u"GERENTE UNI.",
    u"GERENTE": u"GERENTE",
    u"INTER.SUP.": u"INTER.SUP.",
    u"INTERVENTOR": u"INTERVENTOR",
    u"INTERVJUDIC": u"INTERVJUDIC",
    u"INTERVSUSPG": u"INTERVSUSPG",
    u"L. ASESOR": u"L. ASESOR",
    u"LETRAD.ASES.": u"LETRAD.ASES.",
    u"LIQ.CONC.": u"LIQ.CONC.",
    u"LIQ.DEL.MAN": u"LIQ.DEL.MAN",
    u"LIQC": u"LIQC",
    u"LIQMANC": u"LIQMANC",
    u"LIQSOLID": u"LIQSOLID",
    u"LIQUID.CONC.": u"LIQUID.CONC.",
    u"LIQUID.MANC": u"LIQUID.MANC",
    u"LIQUID.MANC.": u"LIQUID.MANC.",
    u"LIQUIDADOR M": u"LIQUIDADOR M",
    u"LIQUIDADOR": u"LIQUIDADOR",
    u"LIQUISOLI": u"LIQUISOLI",
    u"LIQUNICO": u"LIQUNICO",
    u"M.COM.EJ": u"M.COM.EJ",
    u"M.COM.EJEC": u"M.COM.EJEC",
    u"M.COM.NOM.RE": u"M.COM.NOM.RE",
    u"M.COMIT.AUD": u"M.COMIT.AUD",
    u"M.CONS.LIQ": u"M.CONS.LIQ",
    u"MBRO.COM.AUD": u"MBRO.COM.AUD",
    u"MBRO.COM.CTO": u"MBRO.COM.CTO",
    u"MBRO.COM.EJE": u"MBRO.COM.EJE",
    u"MBRO.CTE.NYR": u"MBRO.CTE.NYR",
    u"MBRO.JTA.DIR": u"MBRO.JTA.DIR",
    u"MICORIES": u"MICORIES",
    u"MIE.CONS.REC": u"MIE.CONS.REC",
    u"MIEM.A.G.P.V": u"MIEM.A.G.P.V",
    u"MIEM.C.RET": u"MIEM.C.RET",
    u"MIEM.COM.CTR": u"MIEM.COM.CTR",
    u"MIEM.COM.EIC": u"MIEM.COM.EIC",
    u"MIEM.COM.EJ.": u"MIEM.COM.EJ.",
    u"MIEM.COM.GER": u"MIEM.COM.GER",
    u"MIEM.COM.LIQ": u"MIEM.COM.LIQ",
    u"MIEM.COMAYR.": u"MIEM.COMAYR.",
    u"MIEM.J.DIR.": u"MIEM.J.DIR.",
    u"MIEM.J.G.P.V": u"MIEM.J.G.P.V",
    u"MIEM.J.REC": u"MIEM.J.REC",
    u"MIEMCOMAUCNT": u"MIEMCOMAUCNT",
    u"MIEMCOMAUCUM": u"MIEMCOMAUCUM",
    u"MIEMCOMDIREC": u"MIEMCOMDIREC",
    u"MMBR.COM.DEL": u"MMBR.COM.DEL",
    u"MRO.COMS.CTR": u"MRO.COMS.CTR",
    u"MRO.COMS.EJE": u"MRO.COMS.EJE",
    u"NO DEFINIDO": u"NO DEFINIDO",
    u"NO.CONS": u"NO.CONS",
    u"P.COM.AYR": u"P.COM.AYR",
    u"PDTE.CTE.NYR": u"PDTE.CTE.NYR",
    u"PR.C.RET": u"PR.C.RET",
    u"PR.COM.NOM.R": u"PR.COM.NOM.R",
    u"PR.CONS.LIQ": u"PR.CONS.LIQ",
    u"PRE.COM.A.YC": u"PRE.COM.A.YC",
    u"PRE.COMS.CTR": u"PRE.COMS.CTR",
    u"PRE.COMS.EJE": u"PRE.COMS.EJE",
    u"PRE.CONS.REC": u"PRE.CONS.REC",
    u"PRECOAUDI": u"PRECOAUDI",
    u"PRECOMAUDIT": u"PRECOMAUDIT",
    u"PRECOMAUDIT.": u"PRECOMAUDIT.",
    u"PRECORIES": u"PRECORIES",
    u"PRECTEADMRES": u"PRECTEADMRES",
    u"PRES. HONOR.": u"PRES. HONOR.",
    u"PRES.A.G.P.V": u"PRES.A.G.P.V",
    u"PRES.COM.CTR": u"PRES.COM.CTR",
    u"PRES.COM.DEL": u"PRES.COM.DEL",
    u"PRES.COM.EJ.": u"PRES.COM.EJ.",
    u"PRES.COM.LIQ": u"PRES.COM.LIQ",
    u"PRES.EJECUT.": u"PRES.EJECUT.",
    u"PRES.HONORI.": u"PRES.HONORI.",
    u"PRES.HONORIF": u"PRES.HONORIF",
    u"PRES.J.DIR.": u"PRES.J.DIR.",
    u"PRES.J.G.P.V": u"PRES.J.G.P.V",
    u"PRES.J.REC": u"PRES.J.REC",
    u"PRES.JUNTA": u"PRES.JUNTA",
    u"PRESCOMAUCUM": u"PRESCOMAUCUM",
    u"PRESCOMDIREC": u"PRESCOMDIREC",
    u"PRESEJECUTIV": u"PRESEJECUTIV",
    u"PRESI.GEST.": u"PRESI.GEST.",
    u"PRESI.JTA.DI": u"PRESI.JTA.DI",
    u"PRESIDENTE": u"PRESIDENTE",
    u"PROMOTOR": u"PROMOTOR",
    u"PTE. C. AUD.": u"PTE. C. AUD.",
    u"PTE.C.EJ": u"PTE.C.EJ",
    u"PTE.COMIT.AU": u"PTE.COMIT.AU",
    u"R.C.P.SOLMAN": u"R.C.P.SOLMAN",
    u"R.L.C.PER.M.": u"R.L.C.PER.M.",
    u"R.L.C.PER.S.": u"R.L.C.PER.S.",
    u"R.L.C.PERMA.": u"R.L.C.PERMA.",
    u"REP.ADM.CONC": u"REP.ADM.CONC",
    u"REP.SUC.": u"REP.SUC.",
    u"REPR.143 RRM": u"REPR.143 RRM",
    u"REPR.PERMAN.": u"REPR.PERMAN.",
    u"REPR.SUCURS.": u"REPR.SUCURS.",
    u"REPRE.FISCAL": u"REPRE.FISCAL",
    u"REPRES.PLAN.": u"REPRES.PLAN.",
    u"REPRESENTAN": u"REPRESENTAN",
    u"REPRESSUPLEN": u"REPRESSUPLEN",
    u"S.NO.MI.CO.E": u"S.NO.MI.CO.E",
    u"SCR": u"SCR",
    u"SCRT.J.DIR.": u"SCRT.J.DIR.",
    u"SE.COM.AYR": u"SE.COM.AYR",
    u"SE.TEC.NO CO": u"SE.TEC.NO CO",
    u"SEC.C.EJ": u"SEC.C.EJ",
    u"SEC.COM.EJ.": u"SEC.COM.EJ.",
    u"SEC.COM.EJE.": u"SEC.COM.EJE.",
    u"SEC.COMIT.AU": u"SEC.COMIT.AU",
    u"SEC.COMS.CTR": u"SEC.COMS.CTR",
    u"SEC.COMS.EJE": u"SEC.COMS.EJE",
    u"SEC.CONS.REC": u"SEC.CONS.REC",
    u"SEC.J.G.P.V": u"SEC.J.G.P.V",
    u"SEC.J.REC": u"SEC.J.REC",
    u"SEC.JTA.DIRE": u"SEC.JTA.DIRE",
    u"SECCMDIRNCON": u"SECCMDIRNCON",
    u"SECCOMAUDIT": u"SECCOMAUDIT",
    u"SECR.COM.CTR": u"SECR.COM.CTR",
    u"SECR.COM.LIQ": u"SECR.COM.LIQ",
    u"SECR.CONS.LI": u"SECR.CONS.LI",
    u"SECR.NO CONS": u"SECR.NO CONS",
    u"SECRCENOCON": u"SECRCENOCON",
    u"SECRCOMDIREC": u"SECRCOMDIREC",
    u"SECRENOCONSJ": u"SECRENOCONSJ",
    u"SECRETARIO": u"SECRETARIO",
    u"SOC.GEST.ACT": u"SOC.GEST.ACT",
    u"SOC.PROF.": u"SOC.PROF.",
    u"SOC.UNI.PROF": u"SOC.UNI.PROF",
    u"SOCGESTOR": u"SOCGESTOR",
    u"SOCIO ÚNICO": u"SOCIO ÚNICO",
    u"SOCIO": u"SOCIO",
    u"SUPL.COMI.C.": u"SUPL.COMI.C.",
    u"SUPLENTE": u"SUPLENTE",
    u"TES.C.REC": u"TES.C.REC",
    u"TES.J.DIR.": u"TES.J.DIR.",
    u"TESORERO": u"TESORERO",
    u"V-P1.COM.CTO": u"V-P1.COM.CTO",
    u"V-PRE.COMS.E": u"V-PRE.COMS.E",
    u"V-SEC NO CON": u"V-SEC NO CON",
    u"V-SEC.COMS.E": u"V-SEC.COMS.E",
    u"V-SEC.JTA.DI": u"V-SEC.JTA.DI",
    u"VCP.CONS.REC": u"VCP.CONS.REC",
    u"VCSEC.NO.CON": u"VCSEC.NO.CON",
    u"VIC.JUNT.REC": u"VIC.JUNT.REC",
    u"VICEPR.1": u"VICEPR.1",
    u"VICEPR.2": u"VICEPR.2",
    u"VICEPRESID.": u"VICEPRESID.",
    u"VICEPRESID.1": u"VICEPRESID.1",
    u"VICEPRESID.2": u"VICEPRESID.2",
    u"VICEPRESID.3": u"VICEPRESID.3",
    u"VICEPRESID.4": u"VICEPRESID.4",
    u"VICEPRESIDEN": u"VICEPRESIDEN",
    u"VICES.COM.CT": u"VICES.COM.CT",
    u"VICESECRET.": u"VICESECRET.",
    u"VICESECRETAR": u"VICESECRETAR",
    u"VICETESO.J.D": u"VICETESO.J.D",
    u"VICPRES C.E": u"VICPRES C.E",
    u"VICSEC C.E": u"VICSEC C.E",
    u"VICSEC.COM.E": u"VICSEC.COM.E",
    u"VICTESJDIREC": u"VICTESJDIREC",
    u"VOC1.JTA.DIR": u"VOC1.JTA.DIR",
    u"VOC3.JTA.DIR": u"VOC3.JTA.DIR",
    u"VOC4.JTA.DIR": u"VOC4.JTA.DIR",
    u"VOC5.JTA.DIR": u"VOC5.JTA.DIR",
    u"VOC6.JTA.DIR": u"VOC6.JTA.DIR",
    u"VOCAL 1": u"VOCAL 1",
    u"VOCAL 2": u"VOCAL 2",
    u"VOCAL JTA.DI": u"VOCAL JTA.DI",
    u"VOCAL.PRIMER": u"VOCAL.PRIMER",
    u"VOCAL.SEGUND": u"VOCAL.SEGUND",
    u"VOCAL.TERCER": u"VOCAL.TERCER",
    u"VOCCOMAUDIT": u"VOCCOMAUDIT",
    u"VOCCOMAUDIT.": u"VOCCOMAUDIT.",
    u"VPR.COM.CTR": u"VPR.COM.CTR",
    u"VPRE.J.G.P.V": u"VPRE.J.G.P.V",
    u"VPTE.J.DIR.": u"VPTE.J.DIR.",
    u"VSEC.J.DIR.": u"VSEC.J.DIR.",
    u"VSECRNOCONSJ": u"VSECRNOCONSJ",
}

len_position = len(POSITION)

POSITION.update(new_dict)

assert len(POSITION) == len_position + len(new_dict)


if __name__ == "__main__":
    for k in POSITION:
        print k.encode("utf-8").upper()
