"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'd7990f71257d84c702efab9dbe42ecde7d8a0645',
              'dirt': '',
              'latest_tag': 'flowtool-githooks-0.7.35',
              'latest_tag_commit': 'd7990f71257d84c702efab9dbe42ecde7d8a0645',
              'latest_tag_version': '0.7.35',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {'flowtool-githooks-0.7.31': 92,
                                       'flowtool-githooks-0.7.32': 39,
                                       'flowtool-githooks-0.7.33': 38,
                                       'flowtool-githooks-0.7.34': 4,
                                       'flowtool-githooks-0.7.35': 0},
              'tag_version': {'normalized': '0.7.35',
                              'release': (0, 7, 35),
                              'version': '0.7.35'}},
 'version': '0.7.35'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
