"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': 'd4b3877192554c64610986186b77b4e9eb95b5f0',
              'dirt': '',
              'latest_tag': 'flowtool-python-0.7.14',
              'latest_tag_commit': 'd4b3877192554c64610986186b77b4e9eb95b5f0',
              'latest_tag_version': '0.7.14',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.11': 98,
                                       'flowtool-python-0.7.12': 93,
                                       'flowtool-python-0.7.13': 91,
                                       'flowtool-python-0.7.14': 0},
              'tag_version': {'normalized': '0.7.14',
                              'release': (0, 7, 14),
                              'version': '0.7.14'}},
 'version': '0.7.14'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
