"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '19bf13439182f5059d53e0a641376e3c5bce4ab1',
              'dirt': '',
              'latest_tag': 'flowtool-versioning-0.7.31',
              'latest_tag_commit': '19bf13439182f5059d53e0a641376e3c5bce4ab1',
              'latest_tag_version': '0.7.31',
              'prefix': 'flowtool-versioning-',
              'prefix_tag_distances': {'flowtool-versioning-0.7.27': 9,
                                       'flowtool-versioning-0.7.28': 7,
                                       'flowtool-versioning-0.7.29': 4,
                                       'flowtool-versioning-0.7.30': 1,
                                       'flowtool-versioning-0.7.31': 0},
              'tag_version': {'normalized': '0.7.31',
                              'release': (0, 7, 31),
                              'version': '0.7.31'}},
 'version': '0.7.31'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
