
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '6CBF1791C05DDED6048A25D1B856CEBE'
    
_lr_action_items = {'QUERY':([0,],[1,]),'IDENTIFIER':([1,4,],[3,5,]),'$end':([2,5,],[0,-33,]),'SLASH':([3,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('unit -> definition_list','unit',1,'p_unit','parsing.py',111),
  ('definition_list -> definition definition_list','definition_list',2,'p_definition_list','parsing.py',118),
  ('definition_list -> definition','definition_list',1,'p_definition_list','parsing.py',119),
  ('definition -> define_service','definition',1,'p_definition','parsing.py',131),
  ('definition -> define_client','definition',1,'p_definition','parsing.py',132),
  ('define_service -> SERVICE IDENTIFIER COLON settings operation_list','define_service',5,'p_define_service','parsing.py',139),
  ('define_service -> SERVICE IDENTIFIER COLON operation_list','define_service',4,'p_define_service','parsing.py',140),
  ('settings -> SETTINGS COLON setting_list','settings',3,'p_settings','parsing.py',151),
  ('setting_list -> setting setting_list','setting_list',2,'p_setting_list','parsing.py',158),
  ('setting_list -> setting','setting_list',1,'p_setting_list','parsing.py',159),
  ('setting -> queue','setting',1,'p_setting','parsing.py',171),
  ('setting -> autoscaling','setting',1,'p_setting','parsing.py',172),
  ('setting -> throttling','setting',1,'p_setting','parsing.py',173),
  ('queue -> QUEUE COLON LIFO','queue',3,'p_queue','parsing.py',180),
  ('queue -> QUEUE COLON FIFO','queue',3,'p_queue','parsing.py',181),
  ('throttling -> THROTTLING COLON NONE','throttling',3,'p_throttling','parsing.py',195),
  ('throttling -> THROTTLING COLON TAIL_DROP OPEN_BRACKET NUMBER CLOSE_BRACKET','throttling',6,'p_throttling','parsing.py',196),
  ('autoscaling -> AUTOSCALING COLON autoscaling_setting_list','autoscaling',3,'p_autoscaling','parsing.py',206),
  ('autoscaling_setting_list -> autoscaling_setting autoscaling_setting_list','autoscaling_setting_list',2,'p_autoscaling_setting_list','parsing.py',213),
  ('autoscaling_setting_list -> autoscaling_setting','autoscaling_setting_list',1,'p_autoscaling_setting_list','parsing.py',214),
  ('autoscaling_setting -> PERIOD COLON NUMBER','autoscaling_setting',3,'p_autoscaling_setting','parsing.py',226),
  ('autoscaling_setting -> LIMITS COLON OPEN_SQUARE_BRACKET NUMBER COMMA NUMBER CLOSE_SQUARE_BRACKET','autoscaling_setting',7,'p_autoscaling_setting','parsing.py',227),
  ('operation_list -> define_operation operation_list','operation_list',2,'p_operation_list','parsing.py',239),
  ('operation_list -> define_operation','operation_list',1,'p_operation_list','parsing.py',240),
  ('define_client -> CLIENT IDENTIFIER COLON EVERY NUMBER COLON action_list','define_client',7,'p_define_client','parsing.py',252),
  ('define_operation -> OPERATION IDENTIFIER COLON action_list','define_operation',4,'p_define_operation','parsing.py',259),
  ('action_list -> action action_list','action_list',2,'p_action_list','parsing.py',266),
  ('action_list -> action','action_list',1,'p_action_list','parsing.py',267),
  ('action -> invoke','action',1,'p_action','parsing.py',279),
  ('action -> query','action',1,'p_action','parsing.py',280),
  ('action -> think','action',1,'p_action','parsing.py',281),
  ('think -> THINK NUMBER','think',2,'p_think','parsing.py',288),
  ('query -> QUERY IDENTIFIER SLASH IDENTIFIER','query',4,'p_query','parsing.py',295),
  ('invoke -> INVOKE IDENTIFIER SLASH IDENTIFIER','invoke',4,'p_invoke','parsing.py',302),
]
