"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '8bafddc79313e0a22d960b4fbe4df12ca367de0d',
              'dirt': '',
              'latest_tag': 'flowtool-python-0.7.43',
              'latest_tag_commit': '8bafddc79313e0a22d960b4fbe4df12ca367de0d',
              'latest_tag_version': '0.7.43',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.11': 278,
                                       'flowtool-python-0.7.12': 273,
                                       'flowtool-python-0.7.13': 271,
                                       'flowtool-python-0.7.14': 180,
                                       'flowtool-python-0.7.15': 177,
                                       'flowtool-python-0.7.16': 176,
                                       'flowtool-python-0.7.17': 175,
                                       'flowtool-python-0.7.18': 171,
                                       'flowtool-python-0.7.19': 151,
                                       'flowtool-python-0.7.20': 149,
                                       'flowtool-python-0.7.21': 148,
                                       'flowtool-python-0.7.22': 147,
                                       'flowtool-python-0.7.23': 146,
                                       'flowtool-python-0.7.24': 142,
                                       'flowtool-python-0.7.25': 141,
                                       'flowtool-python-0.7.26': 139,
                                       'flowtool-python-0.7.27': 133,
                                       'flowtool-python-0.7.28': 130,
                                       'flowtool-python-0.7.29': 128,
                                       'flowtool-python-0.7.30': 127,
                                       'flowtool-python-0.7.31': 119,
                                       'flowtool-python-0.7.32': 118,
                                       'flowtool-python-0.7.33': 103,
                                       'flowtool-python-0.7.34': 90,
                                       'flowtool-python-0.7.35': 86,
                                       'flowtool-python-0.7.36': 77,
                                       'flowtool-python-0.7.37': 50,
                                       'flowtool-python-0.7.38': 27,
                                       'flowtool-python-0.7.39': 24,
                                       'flowtool-python-0.7.40': 19,
                                       'flowtool-python-0.7.41': 8,
                                       'flowtool-python-0.7.42': 2,
                                       'flowtool-python-0.7.43': 0},
              'tag_version': {'normalized': '0.7.43',
                              'release': (0, 7, 43),
                              'version': '0.7.43'}},
 'version': '0.7.43'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
