# Commands to be executed (label: path)
# Specify path to executable for any that isn't be found on PATH.
commands:
  optipng: optipng
  advpng: advpng
  pngcrush: pngcrush
  pngquant: pngquant
  jpegoptim: jpegoptim
  jpegtran: jpegtran
  mozjpeg: jpegtran
  imgmin: imgmin
  gifsicle: gifsicle


# Parameters for commands (label: parameters)
# Use same labels as in command section.
parameters:
  optipng: -force -o7 '{file}'
  advpng: -z4 '{file}s'
  pngcrush: -rem gAMA -rem alla -rem cHRM -rem iCCP -rem sRGB 
            -rem time '{file}' '{output_file}'
  pngquant: --output '{output_file}' '{file}'

  jpegoptim: -f --strip-all '{file}'
  jpegtran: -copy none -progressive -optimize -outfile '{output_file}' '{file}'
  mozjpeg: -copy none -progressive -optimize -outfile '{output_file}' '{file}'
  imgmin: "'{file}' '{output_file}'"

  gifsicle: -O2 '{file}' > '{output_file}'
