"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'f3b81ce845dcf7bc3b69ae47bfd761ed85e9fef0',
              'dirt': '',
              'latest_tag': 'flowtool-git-0.7.16',
              'latest_tag_commit': 'f3b81ce845dcf7bc3b69ae47bfd761ed85e9fef0',
              'latest_tag_version': '0.7.16',
              'prefix': 'flowtool-git-',
              'prefix_tag_distances': {'flowtool-git-0.7.1': 197,
                                       'flowtool-git-0.7.10': 108,
                                       'flowtool-git-0.7.11': 97,
                                       'flowtool-git-0.7.12': 95,
                                       'flowtool-git-0.7.13': 93,
                                       'flowtool-git-0.7.14': 92,
                                       'flowtool-git-0.7.15': 23,
                                       'flowtool-git-0.7.16': 0,
                                       'flowtool-git-0.7.2': 195,
                                       'flowtool-git-0.7.3': 183,
                                       'flowtool-git-0.7.4': 174,
                                       'flowtool-git-0.7.5': 172,
                                       'flowtool-git-0.7.6': 168,
                                       'flowtool-git-0.7.7': 147,
                                       'flowtool-git-0.7.8': 146,
                                       'flowtool-git-0.7.9': 123},
              'tag_version': {'normalized': '0.7.16',
                              'release': (0, 7, 16),
                              'version': '0.7.16'}},
 'version': '0.7.16'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
