
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.2'
version_full = '832e4711b5d09b4787495d8827d141246258093a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

