"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': 'aba626d4344245461e71ad115cf3146db833613a',
              'dirt': '',
              'latest_tag': 'flowtool-base-0.7.38',
              'latest_tag_commit': 'aba626d4344245461e71ad115cf3146db833613a',
              'latest_tag_version': '0.7.38',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {'flowtool-base-0.7.12': 128,
                                       'flowtool-base-0.7.13': 110,
                                       'flowtool-base-0.7.14': 108,
                                       'flowtool-base-0.7.15': 107,
                                       'flowtool-base-0.7.16': 106,
                                       'flowtool-base-0.7.17': 105,
                                       'flowtool-base-0.7.18': 103,
                                       'flowtool-base-0.7.19': 99,
                                       'flowtool-base-0.7.20': 94,
                                       'flowtool-base-0.7.21': 93,
                                       'flowtool-base-0.7.22': 92,
                                       'flowtool-base-0.7.23': 75,
                                       'flowtool-base-0.7.24': 71,
                                       'flowtool-base-0.7.25': 70,
                                       'flowtool-base-0.7.26': 69,
                                       'flowtool-base-0.7.27': 68,
                                       'flowtool-base-0.7.28': 67,
                                       'flowtool-base-0.7.29': 61,
                                       'flowtool-base-0.7.30': 60,
                                       'flowtool-base-0.7.31': 55,
                                       'flowtool-base-0.7.32': 50,
                                       'flowtool-base-0.7.33': 48,
                                       'flowtool-base-0.7.34': 45,
                                       'flowtool-base-0.7.35': 17,
                                       'flowtool-base-0.7.36': 10,
                                       'flowtool-base-0.7.37': 4,
                                       'flowtool-base-0.7.38': 0},
              'tag_version': {'normalized': '0.7.38',
                              'release': (0, 7, 38),
                              'version': '0.7.38'}},
 'version': '0.7.38'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
