sudo: false
language: python
python:
- 2.7
- 3.5
script:
- pip install -U pytest
- python setup.py test --extras
deploy:
  provider: pypi
  on:
    tags: true
    all_branches: true
  user: jaraco
  distributions: release
  python: 3.5
  password:
    secure: h07gd6xPThamwJM3u1tn1KIcNKaBeNvvNOVLBGv7ikeZDJjzGmDDJGcpY4RasLyCh4RDvhRInF98AOG0PHzepJpCX0pJOMI9BlenD4S6Q8OvfOEUaW2MWQAEiLFraSp1AidiZbI5iaIymCIyyJxwWmok2mvUe9v7AQEwLSqpWokoUZdxC/uZTZwXPHobTvhtkk6ZXAYnRlnHD/iyzN2GcmDscjJ9dPbcJwTMKIG9rRjYg78wlKEtGEjDKVS2FykoMI3kG+WEmuIo4N9FUfSSW7pn56Qx7Knf6u5Q6vqnIYaWtTJDNgVcQb3nqlZ7MJYfzt4yPnlxCmjY+syLzV6/hMNhkO10r2vJSPFbARmmq58TEaMzvAJxy6bEiwWiz8inXk3YKaIQyISrEvF0j+OIChfJhOZ8fNVgBWb/snvMShGRZw6I/Uv6aMYvEqMrTgxhqWA44OULhZOTOlIq5fDwGudtBOMYGGMzEFfHvWZVXMG/BXDYxUclwAgzMWiAfK2wF3V5a/Y/eRWqhUq7mpmwFra8VmaHBVetJmHk7gkDaeSD0PPj8OBnByb2rvWLScEHCS/eFP/Yw83BbxU6lH9nrTfcZp1y54BA6tKOGWHrGoekb0fEncik9IqfljLcfPhG4M4B5BlcTCVuwjRMQSztOCeFW76DJ3gZt+dKV2BSWlM=
