__version__ = "0.1.3"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v0.1.3)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'd88f8d3c12fbd720ff7c3d47d5d8a644b444bf0e'
__git_head_subject__ = 'Finished Release v0.1.3'
__git_head_message__ = ''
__git_dirty_diff__ = ''
__git_commit_date__ = '2016-04-03 12:59:59'
