---
- hosts: all
#  sudo: yes
  become: yes
  become_method: sudo
  vars:
    ANSIBLE_VERSION: 1.9.4
  tasks:
    - name: Install libselinux-python in RH
      action: yum pkg=libselinux-python state=installed
      when: ansible_os_family == "RedHat"
  
    - name: Apt-get update
      apt: update_cache=yes
      when: ansible_os_family == "Debian"

    - name: EPEL
      template: src=utils/templates/epel.repo dest=/etc/yum.repos.d/epel.repo
      #template: src=utils/templates/epel-es.repo dest=/etc/yum.repos.d/epel.repo
      when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"
    
    - name: Apt install requirements
      apt: name=unzip,gcc,python-dev,openssh-client,sshpass
      when: ansible_os_family == "Debian"

    - name: Yum install requirements RH6 or Fedora
      yum: name=python-distribute,gcc,python-devel,wget,openssh-clients,sshpass
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= 6
    
    - name: Yum install requirements RH5
      yum: name=python26,python26-simplejson,python26-distribute,gcc,python26-devel,openssh-clients,sshpass
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version < 6

    - name: Zypper install requirements Suse
      action: command zypper -n install python python-pip gcc python-devel wget   
      when: ansible_os_family == "Suse"

    - name: Install Pip from distribution repositories
      apt: name=python-pip
      when: ansible_os_family == "Debian" and not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version < 14)

    - name: Install Pip 2.6
      action: command easy_install-2.6 pip==1.4.1
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version < 6
      
    - name: Install Pip
      easy_install: name=pip
      when: ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version >= 6)
      register: result_install_pip
      ignore_errors: True

    - name: Install Pip (alternative)
      shell: wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py && python get-pip.py
      when: result_install_pip|failed

    - name: Link python 
      file: src=/usr/bin/python dest=/usr/bin/python_ansible state=link
      when: ansible_os_family == "Suse" or ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version >= 6)

    - name: Link python 2.6
      file: src=/usr/bin/python2.6 dest=/usr/bin/python_ansible state=link
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version < 6

    - name: Install ansible with Pip
      pip: name=ansible version={{ ANSIBLE_VERSION }}
      when: ansible_os_family == "Suse" or ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version >= 6)
      
    - name: Install ansible with Pip 2.6
      action: command pip-2.6 install ansible=={{ ANSIBLE_VERSION }}
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version < 6
      
    - name: Install scp with Pip
      pip: name=scp
      when: ansible_os_family == "Suse" or ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version >= 6)
      
    - name: Install scp with Pip 2.6
      action: command pip-2.6 install scp
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version < 6
      
    - name: Install pywinrm for windows support in ansible with Pip
      pip: name=http://github.com/diyan/pywinrm/archive/master.zip#egg=pywinrm
      when: ansible_os_family == "Suse" or ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version >= 6)
      
    - name: Install pywinrm for windows support in ansible with Pip 2.6
      action: command pip-2.6 install http://github.com/diyan/pywinrm/archive/master.zip#egg=pywinrm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version < 6

    - name: Disable SELinux
      selinux: state=disabled
      when: ansible_os_family == "RedHat"
      ignore_errors: yes
      
    - name: Create /etc/ansible
      file: path=/etc/ansible state=directory
      
    - name: Set host_key_checking to false in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=host_key_checking value=False

    - name: Set transport to ssh in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=transport value=ssh
      when: ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version >= 6)  or (ansible_os_family == "Suse" and ansible_distribution_major_version >= 10)
      
    - name: Set transport to smart in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=transport value=smart
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version < 6) or (ansible_os_family == "Suse" and ansible_distribution_major_version < 10)

    - name: Change ssh_args to set ControlPersist to 15 min in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=ssh_connection option=ssh_args value="-o ControlMaster=auto -o ControlPersist=900s"
      when: ansible_os_family == "Debian" or (ansible_os_family == "RedHat" and ansible_distribution_major_version >= 7) or (ansible_os_family == "Suse" and ansible_distribution_major_version >= 12)
      
    - name: Change ssh_args to remove ControlPersist in REL 6 and older in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=ssh_connection option=ssh_args value=""
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version < 7) or (ansible_os_family == "Suse" and ansible_distribution_major_version < 12)
      
    - name: Activate SSH pipelining in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=ssh_connection option=pipelining value=True

    - name: Set jinja2.ext.do to jinja2_extensions in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=jinja2_extensions value=jinja2.ext.do
