"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '73a170c883ae4a2339ebfb120409c3efed463523',
              'dirt': '',
              'latest_tag': 'flowtool-versioning-0.7.50',
              'latest_tag_commit': '73a170c883ae4a2339ebfb120409c3efed463523',
              'latest_tag_version': '0.7.50',
              'prefix': 'flowtool-versioning-',
              'prefix_tag_distances': {'flowtool-versioning-0.7.47': 9,
                                       'flowtool-versioning-0.7.48': 3,
                                       'flowtool-versioning-0.7.49': 1,
                                       'flowtool-versioning-0.7.50': 0},
              'tag_version': {'normalized': '0.7.50',
                              'release': (0, 7, 50),
                              'version': '0.7.50'}},
 'version': '0.7.50'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
