"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '8d0f8eadaa21b18d470fb66b7168638dacbb56f9',
              'dirt': '',
              'latest_tag': 'flowtool-git-0.7.13',
              'latest_tag_commit': '8d0f8eadaa21b18d470fb66b7168638dacbb56f9',
              'latest_tag_version': '0.7.13',
              'prefix': 'flowtool-git-',
              'prefix_tag_distances': {'flowtool-git-0.7.10': 15,
                                       'flowtool-git-0.7.11': 4,
                                       'flowtool-git-0.7.12': 2,
                                       'flowtool-git-0.7.13': 0,
                                       'flowtool-git-0.7.7': 54,
                                       'flowtool-git-0.7.8': 53,
                                       'flowtool-git-0.7.9': 30},
              'tag_version': {'normalized': '0.7.13',
                              'release': (0, 7, 13),
                              'version': '0.7.13'}},
 'version': '0.7.13'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
