language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - travis_retry pip install pyflakes flake8 wheel setuptools virtualenv discover flake8-docstrings
before_script:
  - git config --global user.email "foo@example.com"
  - git config --global user.name "foo"
script:
  - easy_install --version
  - virtualenv --version
  - python setup.py make_versioneer

  - python -m discover test
  - python test/git/test_git.py -v
  - python test/git/test_invocations.py -v

  - python setup.py make_long_version_py_git

  - pyflakes setup.py versioneer.py git_version.py
  - find src -iname "*.py"
    -not -path "src/git/long_header.py"
    -not -path "src/header.py"
    -exec pyflakes {} \;
    -exec echo "{}" \;
  - pyflakes test

  - flake8 git_version.py versioneer.py
