
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2d2f502fdd3794e46004d489d27bbfb5574bbdc0",
 "version": "1.1.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
