"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'fcefa27ac72c8a24167623a6080438ed86acf04f',
              'dirt': '',
              'latest_tag': 'flowtool-demo-githooks-0.7.12',
              'latest_tag_commit': 'fcefa27ac72c8a24167623a6080438ed86acf04f',
              'latest_tag_version': '0.7.12',
              'prefix': 'flowtool-demo-githooks-',
              'prefix_tag_distances': {'flowtool-demo-githooks-0.7.10': 21,
                                       'flowtool-demo-githooks-0.7.11': 9,
                                       'flowtool-demo-githooks-0.7.12': 0,
                                       'flowtool-demo-githooks-0.7.6': 130,
                                       'flowtool-demo-githooks-0.7.7': 107,
                                       'flowtool-demo-githooks-0.7.8': 40,
                                       'flowtool-demo-githooks-0.7.9': 34},
              'tag_version': {'normalized': '0.7.12',
                              'release': (0, 7, 12),
                              'version': '0.7.12'}},
 'version': '0.7.12'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
