"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': u'0f02b834eab8bb0542d15945f66704e138c8e6c7',
              'dirt': u'',
              'latest_tag': u'flowtool-versioning-0.7.15',
              'latest_tag_commit': u'0f02b834eab8bb0542d15945f66704e138c8e6c7',
              'latest_tag_version': u'0.7.15',
              'prefix': 'flowtool-versioning-',
              'prefix_tag_distances': {u'flowtool-versioning-0.7.11': 5,
                                       u'flowtool-versioning-0.7.12': 4,
                                       u'flowtool-versioning-0.7.13': 3,
                                       u'flowtool-versioning-0.7.14': 1,
                                       u'flowtool-versioning-0.7.15': 0},
              'tag_version': {'normalized': '0.7.15',
                              'release': (0, 7, 15),
                              'version': u'0.7.15'}},
 'version': u'0.7.15'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
