
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "454f9174f62e81196b5a358cc71ce3fd13948ebf",
 "version": "1.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
