"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'b6be36c587d8b7d8577ac01b94dacb96191dd6d7',
              'dirt': '',
              'latest_tag': 'flowtool-python-0.7.39',
              'latest_tag_commit': 'b6be36c587d8b7d8577ac01b94dacb96191dd6d7',
              'latest_tag_version': '0.7.39',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.11': 254,
                                       'flowtool-python-0.7.12': 249,
                                       'flowtool-python-0.7.13': 247,
                                       'flowtool-python-0.7.14': 156,
                                       'flowtool-python-0.7.15': 153,
                                       'flowtool-python-0.7.16': 152,
                                       'flowtool-python-0.7.17': 151,
                                       'flowtool-python-0.7.18': 147,
                                       'flowtool-python-0.7.19': 127,
                                       'flowtool-python-0.7.20': 125,
                                       'flowtool-python-0.7.21': 124,
                                       'flowtool-python-0.7.22': 123,
                                       'flowtool-python-0.7.23': 122,
                                       'flowtool-python-0.7.24': 118,
                                       'flowtool-python-0.7.25': 117,
                                       'flowtool-python-0.7.26': 115,
                                       'flowtool-python-0.7.27': 109,
                                       'flowtool-python-0.7.28': 106,
                                       'flowtool-python-0.7.29': 104,
                                       'flowtool-python-0.7.30': 103,
                                       'flowtool-python-0.7.31': 95,
                                       'flowtool-python-0.7.32': 94,
                                       'flowtool-python-0.7.33': 79,
                                       'flowtool-python-0.7.34': 66,
                                       'flowtool-python-0.7.35': 62,
                                       'flowtool-python-0.7.36': 53,
                                       'flowtool-python-0.7.37': 26,
                                       'flowtool-python-0.7.38': 3,
                                       'flowtool-python-0.7.39': 0},
              'tag_version': {'normalized': '0.7.39',
                              'release': (0, 7, 39),
                              'version': '0.7.39'}},
 'version': '0.7.39'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
