# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatstate',
            name='chat',
            field=models.ForeignKey(help_text='Chat in Telegram API format. https://core.telegram.org/bots/api#chat', on_delete=django.db.models.deletion.CASCADE, related_name='chatstates', to='microbot.Chat', verbose_name='Chat'),
        ),
    ]
