# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0006_assignee_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='allow_access',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permission',
            name='deny_access',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deny_access_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
