
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "55ae04f66ab61516027cbb0b1378f5247a40b5a1",
 "version": "0.2.post18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
