"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '3093254b1c395fc53018bb18c07f71da3d559fe3',
              'dirt': '',
              'latest_tag': 'flowtool-base-0.7.27',
              'latest_tag_commit': '3093254b1c395fc53018bb18c07f71da3d559fe3',
              'latest_tag_version': '0.7.27',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {'flowtool-base-0.7.12': 60,
                                       'flowtool-base-0.7.13': 42,
                                       'flowtool-base-0.7.14': 40,
                                       'flowtool-base-0.7.15': 39,
                                       'flowtool-base-0.7.16': 38,
                                       'flowtool-base-0.7.17': 37,
                                       'flowtool-base-0.7.18': 35,
                                       'flowtool-base-0.7.19': 31,
                                       'flowtool-base-0.7.20': 26,
                                       'flowtool-base-0.7.21': 25,
                                       'flowtool-base-0.7.22': 24,
                                       'flowtool-base-0.7.23': 7,
                                       'flowtool-base-0.7.24': 3,
                                       'flowtool-base-0.7.25': 2,
                                       'flowtool-base-0.7.26': 1,
                                       'flowtool-base-0.7.27': 0},
              'tag_version': {'normalized': '0.7.27',
                              'release': (0, 7, 27),
                              'version': '0.7.27'}},
 'version': '0.7.27'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
