
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6'
version_full = 'ba0224d250ebb22ea5fa4cb76c3bc23406ffaaf8'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

