
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.3'
version_full = '790a13e045ebde03af5a3d24e485ec6ab143a3b4'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

