__author__ = "Scott Sharkey"
__copyright__ = "Copyright 2015-16"
__license__ = "BSD"
__version__ = "0.0.3"
__email__ = "ssharkey@lanshark.com"
__status__ = "Development"
__url__ = "https://github.com/lanshark/barchart-ondemand-client-python"
