"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '2042ae6e4284d01bfdad1175c1b85e17683a423c',
              'dirt': '',
              'latest_tag': 'flowtool-git-0.7.19',
              'latest_tag_commit': '2042ae6e4284d01bfdad1175c1b85e17683a423c',
              'latest_tag_version': '0.7.19',
              'prefix': 'flowtool-git-',
              'prefix_tag_distances': {'flowtool-git-0.7.17': 135,
                                       'flowtool-git-0.7.18': 66,
                                       'flowtool-git-0.7.19': 0},
              'tag_version': {'normalized': '0.7.19',
                              'release': (0, 7, 19),
                              'version': '0.7.19'}},
 'version': '0.7.19'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
