"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '19158f13cebca3bcb02f78e81d258bc467580798',
              'dirt': '',
              'latest_tag': 'flowtool-all-0.7.13',
              'latest_tag_commit': '19158f13cebca3bcb02f78e81d258bc467580798',
              'latest_tag_version': '0.7.13',
              'prefix': 'flowtool-all-',
              'prefix_tag_distances': {'flowtool-all-0.7.10': 193,
                                       'flowtool-all-0.7.11': 187,
                                       'flowtool-all-0.7.12': 105,
                                       'flowtool-all-0.7.13': 0},
              'tag_version': {'normalized': '0.7.13',
                              'release': (0, 7, 13),
                              'version': '0.7.13'}},
 'version': '0.7.13'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
