"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'c8bb1d664ad06a7a7111a685deef55b9c3e8098f',
              'dirt': '',
              'latest_tag': 'flowtool-python-0.7.37',
              'latest_tag_commit': 'c8bb1d664ad06a7a7111a685deef55b9c3e8098f',
              'latest_tag_version': '0.7.37',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.34': 40,
                                       'flowtool-python-0.7.35': 36,
                                       'flowtool-python-0.7.36': 27,
                                       'flowtool-python-0.7.37': 0},
              'tag_version': {'normalized': '0.7.37',
                              'release': (0, 7, 37),
                              'version': '0.7.37'}},
 'version': '0.7.37'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
