# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0014_auto_20160404_1908'),
        ('frequently', '0002_auto_20150911_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyEntryCategoryPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('categories', models.ManyToManyField(related_name='cmsplugin_frequently_entrycategoryplugins', to='frequently.EntryCategory', verbose_name='Categories')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
