
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.3'
version_full = '8a4eb4f5675628bc8ee2d0da70b9e9397f80c280'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

