"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '19141a91aaf1097fcd00680ab065ffa253bfe6aa',
              'dirt': '',
              'latest_tag': 'flowtool-base-0.7.39',
              'latest_tag_commit': '19141a91aaf1097fcd00680ab065ffa253bfe6aa',
              'latest_tag_version': '0.7.39',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {'flowtool-base-0.7.36': 46,
                                       'flowtool-base-0.7.37': 40,
                                       'flowtool-base-0.7.38': 36,
                                       'flowtool-base-0.7.39': 0},
              'tag_version': {'normalized': '0.7.39',
                              'release': (0, 7, 39),
                              'version': '0.7.39'}},
 'version': '0.7.39'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
