"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': 'b838fae3c2d1a311a0d4668b6a65685e2c6c699f',
              'dirt': '',
              'latest_tag': 'flowtool-gitflow-0.7.13',
              'latest_tag_commit': 'b838fae3c2d1a311a0d4668b6a65685e2c6c699f',
              'latest_tag_version': '0.7.13',
              'prefix': 'flowtool-gitflow-',
              'prefix_tag_distances': {'flowtool-gitflow-0.7.10': 48,
                                       'flowtool-gitflow-0.7.11': 42,
                                       'flowtool-gitflow-0.7.12': 29,
                                       'flowtool-gitflow-0.7.13': 0,
                                       'flowtool-gitflow-0.7.8': 77,
                                       'flowtool-gitflow-0.7.9': 63},
              'tag_version': {'normalized': '0.7.13',
                              'release': (0, 7, 13),
                              'version': '0.7.13'}},
 'version': '0.7.13'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
