"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '51c132aaacb8d807f55582f31ca63e8ceb8b0144',
              'dirt': '',
              'latest_tag': 'flowtool-githooks-0.7.30',
              'latest_tag_commit': '51c132aaacb8d807f55582f31ca63e8ceb8b0144',
              'latest_tag_version': '0.7.30',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {'flowtool-githooks-0.7.13': 200,
                                       'flowtool-githooks-0.7.14': 177,
                                       'flowtool-githooks-0.7.15': 131,
                                       'flowtool-githooks-0.7.16': 123,
                                       'flowtool-githooks-0.7.17': 122,
                                       'flowtool-githooks-0.7.18': 121,
                                       'flowtool-githooks-0.7.19': 118,
                                       'flowtool-githooks-0.7.20': 97,
                                       'flowtool-githooks-0.7.21': 84,
                                       'flowtool-githooks-0.7.22': 82,
                                       'flowtool-githooks-0.7.23': 78,
                                       'flowtool-githooks-0.7.24': 76,
                                       'flowtool-githooks-0.7.25': 73,
                                       'flowtool-githooks-0.7.26': 46,
                                       'flowtool-githooks-0.7.27': 30,
                                       'flowtool-githooks-0.7.28': 19,
                                       'flowtool-githooks-0.7.29': 12,
                                       'flowtool-githooks-0.7.30': 0},
              'tag_version': {'normalized': '0.7.30',
                              'release': (0, 7, 30),
                              'version': '0.7.30'}},
 'version': '0.7.30'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
