application: {{ application }}
version: 0-0-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# APP STATS
- url: /stats(/.*)?
  script: google.appengine.ext.appstats.ui.app
  
# API SCRIPT
- url: .*
  script: app.app

# LIBRARIES
libraries:
- name: webapp2
  version: "2.5.1"

builtins:
- appstats: on
- remote_api: on