"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '5b4ba05392fd8cf35609e4ac61b68fc3523a219f',
              'dirt': '',
              'latest_tag': 'flowtool-python-0.7.21',
              'latest_tag_commit': '5b4ba05392fd8cf35609e4ac61b68fc3523a219f',
              'latest_tag_version': '0.7.21',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.11': 130,
                                       'flowtool-python-0.7.12': 125,
                                       'flowtool-python-0.7.13': 123,
                                       'flowtool-python-0.7.14': 32,
                                       'flowtool-python-0.7.15': 29,
                                       'flowtool-python-0.7.16': 28,
                                       'flowtool-python-0.7.17': 27,
                                       'flowtool-python-0.7.18': 23,
                                       'flowtool-python-0.7.19': 3,
                                       'flowtool-python-0.7.20': 1,
                                       'flowtool-python-0.7.21': 0},
              'tag_version': {'normalized': '0.7.21',
                              'release': (0, 7, 21),
                              'version': '0.7.21'}},
 'version': '0.7.21'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
