"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '71e2cbb0bebc8be9c798507d58da7f46b7172783',
              'dirt': '',
              'latest_tag': 'asciidrumming-cli-0.3.3',
              'latest_tag_commit': '71e2cbb0bebc8be9c798507d58da7f46b7172783',
              'latest_tag_version': '0.3.3',
              'prefix': 'asciidrumming-cli-',
              'prefix_tag_distances': {'asciidrumming-cli-0.3.0': 9,
                                       'asciidrumming-cli-0.3.1': 8,
                                       'asciidrumming-cli-0.3.2': 4,
                                       'asciidrumming-cli-0.3.3': 0},
              'tag_version': {'normalized': '0.3.3',
                              'release': (0, 3, 3),
                              'version': '0.3.3'}},
 'version': '0.3.3'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
