"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '9cb905c0fa7348a71ba1e6c520a52373f8d331f7',
              'dirt': '',
              'latest_tag': 'flowtool-versioning-0.7.23',
              'latest_tag_commit': '9cb905c0fa7348a71ba1e6c520a52373f8d331f7',
              'latest_tag_version': '0.7.23',
              'prefix': 'flowtool-versioning-',
              'prefix_tag_distances': {'flowtool-versioning-0.7.11': 37,
                                       'flowtool-versioning-0.7.12': 36,
                                       'flowtool-versioning-0.7.13': 35,
                                       'flowtool-versioning-0.7.14': 33,
                                       'flowtool-versioning-0.7.15': 32,
                                       'flowtool-versioning-0.7.16': 29,
                                       'flowtool-versioning-0.7.17': 27,
                                       'flowtool-versioning-0.7.18': 25,
                                       'flowtool-versioning-0.7.19': 24,
                                       'flowtool-versioning-0.7.20': 22,
                                       'flowtool-versioning-0.7.21': 19,
                                       'flowtool-versioning-0.7.22': 7,
                                       'flowtool-versioning-0.7.23': 0},
              'tag_version': {'normalized': '0.7.23',
                              'release': (0, 7, 23),
                              'version': '0.7.23'}},
 'version': '0.7.23'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
