
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e4a61c6824f5f06e059d37dc661a95dceaf87d6d",
 "version": "0.4.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
