"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': u'bb45b50fbc6d6ac917ed69a98fd9347b4b44406d',
              'dirt': u'',
              'latest_tag': u'flowtool-base-0.7.28',
              'latest_tag_commit': u'bb45b50fbc6d6ac917ed69a98fd9347b4b44406d',
              'latest_tag_version': u'0.7.28',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {u'flowtool-base-0.7.12': 61,
                                       u'flowtool-base-0.7.13': 43,
                                       u'flowtool-base-0.7.14': 41,
                                       u'flowtool-base-0.7.15': 40,
                                       u'flowtool-base-0.7.16': 39,
                                       u'flowtool-base-0.7.17': 38,
                                       u'flowtool-base-0.7.18': 36,
                                       u'flowtool-base-0.7.19': 32,
                                       u'flowtool-base-0.7.20': 27,
                                       u'flowtool-base-0.7.21': 26,
                                       u'flowtool-base-0.7.22': 25,
                                       u'flowtool-base-0.7.23': 8,
                                       u'flowtool-base-0.7.24': 4,
                                       u'flowtool-base-0.7.25': 3,
                                       u'flowtool-base-0.7.26': 2,
                                       u'flowtool-base-0.7.27': 1,
                                       u'flowtool-base-0.7.28': 0},
              'tag_version': {'normalized': '0.7.28',
                              'release': (0, 7, 28),
                              'version': u'0.7.28'}},
 'version': u'0.7.28'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
