"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'f3b81ce845dcf7bc3b69ae47bfd761ed85e9fef0',
              'dirt': '',
              'latest_tag': 'flowtool-python-0.7.35',
              'latest_tag_commit': 'f3b81ce845dcf7bc3b69ae47bfd761ed85e9fef0',
              'latest_tag_version': '0.7.35',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.11': 192,
                                       'flowtool-python-0.7.12': 187,
                                       'flowtool-python-0.7.13': 185,
                                       'flowtool-python-0.7.14': 94,
                                       'flowtool-python-0.7.15': 91,
                                       'flowtool-python-0.7.16': 90,
                                       'flowtool-python-0.7.17': 89,
                                       'flowtool-python-0.7.18': 85,
                                       'flowtool-python-0.7.19': 65,
                                       'flowtool-python-0.7.20': 63,
                                       'flowtool-python-0.7.21': 62,
                                       'flowtool-python-0.7.22': 61,
                                       'flowtool-python-0.7.23': 60,
                                       'flowtool-python-0.7.24': 56,
                                       'flowtool-python-0.7.25': 55,
                                       'flowtool-python-0.7.26': 53,
                                       'flowtool-python-0.7.27': 47,
                                       'flowtool-python-0.7.28': 44,
                                       'flowtool-python-0.7.29': 42,
                                       'flowtool-python-0.7.30': 41,
                                       'flowtool-python-0.7.31': 33,
                                       'flowtool-python-0.7.32': 32,
                                       'flowtool-python-0.7.33': 17,
                                       'flowtool-python-0.7.34': 4,
                                       'flowtool-python-0.7.35': 0},
              'tag_version': {'normalized': '0.7.35',
                              'release': (0, 7, 35),
                              'version': '0.7.35'}},
 'version': '0.7.35'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
