name: supervisor
author: Ajenti project
email: e@ajenti.org
url: http://ajenti.org
version: '0.14'
title: 'Supervisor'
icon: play
dependencies:
    - !!python/object:aj.plugins.PluginDependency { plugin_name: core }
    - !!python/object:aj.plugins.PluginDependency { plugin_name: augeas }
    - !!python/object:aj.plugins.PluginDependency { plugin_name: services }
    - !!python/object:aj.plugins.PluginDependency { plugin_name: passwd }
    - !!python/object:aj.plugins.BinaryDependency { binary_name: supervisorctl }
resources:
    - 'resources/js/module.coffee'
    - 'resources/js/routing.coffee'
    - 'resources/js/controllers/index.controller.coffee'
    - 'resources/partial/index.html'
    - 'ng:ajenti.supervisor'
