# Input files ------------------------------------------------------------------
reference: reference.fa
input_bam: ERR036019_sorted.bam

# Output prefix ----------------------------------------------------------------
output: ERR036019

# Software params --------------------------------------------------------------
read_group:
    RGID=: 1
    RGLB=: lib1
    RGPL=: illumina
    RGPU=: unit1
    RGSM=: 20

markduplicate: yes

freebayes:
    --ploidy: 1

vcf_filter:
    QUAL: 10000
    FREQ: 0.85
    INFO:
        DP: ">= 10"
        SAP: "< 100"

# Path of jar for picard-tools
picard_jar: 
# Path of jar for GATK
gatk_jar: 

# Module load ------------------------------------------------------------------
# Do you use it on a cluster ?
on_cluster: no
# Set the path of the module sources.
src_module: /etc/profile.d/pasteur_modules.sh
# Set versions of modules
picard_module: picard-tools/1.94
bwa_module: bwa/0.7.5a
samtools_module: samtools/1.2
gatk_module: GenomeAnalysisTK/3.4-0
freebayes_module: freebayes/v1.0.2
