language: python
sudo: false
# We need ghostscript at least 9.15 and japanese minch fonts
addons:
    apt:
        sources:
        - debian-sid
        packages:
        - ghostscript
        - fonts-takao-mincho
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
install:
    - travis_retry pip install tox
script:
    - tox
notifications:
    email: false
