"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'c5045ced62cfeacc264f32913e1050c37e55f596',
              'dirt': '',
              'latest_tag': 'data-pypes-0.1.6',
              'latest_tag_commit': 'c5045ced62cfeacc264f32913e1050c37e55f596',
              'latest_tag_version': '0.1.6',
              'prefix': 'data-pypes-',
              'prefix_tag_distances': {'data-pypes-0.1.1': 17,
                                       'data-pypes-0.1.2': 15,
                                       'data-pypes-0.1.3': 13,
                                       'data-pypes-0.1.4': 8,
                                       'data-pypes-0.1.5': 2,
                                       'data-pypes-0.1.6': 0},
              'tag_version': {'normalized': '0.1.6',
                              'release': (0, 1, 6),
                              'version': '0.1.6'}},
 'version': '0.1.6'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
