"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '6ee7fb81b55adb62fbb4b6911f82c0b7904dc26a',
              'dirt': '',
              'latest_tag': 'flowtool-git-0.7.18',
              'latest_tag_commit': '6ee7fb81b55adb62fbb4b6911f82c0b7904dc26a',
              'latest_tag_version': '0.7.18',
              'prefix': 'flowtool-git-',
              'prefix_tag_distances': {'flowtool-git-0.7.17': 69,
                                       'flowtool-git-0.7.18': 0},
              'tag_version': {'normalized': '0.7.18',
                              'release': (0, 7, 18),
                              'version': '0.7.18'}},
 'version': '0.7.18'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
