# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import simple_email_verification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('verification_token', models.TextField(default=simple_email_verification.models.create_verification_token)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Verified E-Mail Address',
                'verbose_name_plural': 'Verified E-Mail Addresses',
            },
        ),
    ]
