bind:
  address: '0.0.0.0'
  port: 8080
# Keys and values must match the omega rule
proxy:
  profile:
    first: 'http://127.0.0.1:12345'
    second: 'socks5://127.0.0.1:23456'
    direct: 'direct://'
  # Virtual profile as alias
  virtual:
    speed: "first"
omega_file: 'omega.conf'
ipv6_test:
  host: 'www.yahoo.com'
  port: 443