sudo: false
language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5
script:
- pip install -U pytest
- python setup.py test
deploy:
  provider: pypi
  on:
    tags: true
    all_branches: true
    python: 3.5
  user: jaraco
  distributions: release
  password:
    secure: fggUs33qP6DB+j/q7KGScfohgGq7OwsW5BMW6ZZvSlq+9pnNDZxSVrfCw0wb9vdq/Hb9nH4Of+wDoyh+Ul6GN28GRX7qj1HTjbc65nhRp9aA1Ib9Y3KJwGR8k5gPJZmx/zKP0r7COSXsOdXDkVSJ/UjCfuKhcsSHpi0lAYG6BSA=
