"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'f3b81ce845dcf7bc3b69ae47bfd761ed85e9fef0',
              'dirt': '',
              'latest_tag': 'flowtool-githooks-0.7.28',
              'latest_tag_commit': 'f3b81ce845dcf7bc3b69ae47bfd761ed85e9fef0',
              'latest_tag_version': '0.7.28',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {'flowtool-githooks-0.7.13': 181,
                                       'flowtool-githooks-0.7.14': 158,
                                       'flowtool-githooks-0.7.15': 112,
                                       'flowtool-githooks-0.7.16': 104,
                                       'flowtool-githooks-0.7.17': 103,
                                       'flowtool-githooks-0.7.18': 102,
                                       'flowtool-githooks-0.7.19': 99,
                                       'flowtool-githooks-0.7.20': 78,
                                       'flowtool-githooks-0.7.21': 65,
                                       'flowtool-githooks-0.7.22': 63,
                                       'flowtool-githooks-0.7.23': 59,
                                       'flowtool-githooks-0.7.24': 57,
                                       'flowtool-githooks-0.7.25': 54,
                                       'flowtool-githooks-0.7.26': 27,
                                       'flowtool-githooks-0.7.27': 11,
                                       'flowtool-githooks-0.7.28': 0},
              'tag_version': {'normalized': '0.7.28',
                              'release': (0, 7, 28),
                              'version': '0.7.28'}},
 'version': '0.7.28'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
