
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "150ab438b6efa220785d2f6b9f1cf08cc1ffdaad",
 "version": "0.4.post3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
