
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "56fdf071288d79246d375de642a5214bec511623",
 "version": "1.5.0.post4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
