
# This file was generated by 'versioneer.py' (0.13+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.3'
version_full = '30770e42ae08ce5cc46c6d6c4af19e9947066f00'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

