"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'd7990f71257d84c702efab9dbe42ecde7d8a0645',
              'dirt': '',
              'latest_tag': 'flowtool-all-0.7.18',
              'latest_tag_commit': 'd7990f71257d84c702efab9dbe42ecde7d8a0645',
              'latest_tag_version': '0.7.18',
              'prefix': 'flowtool-all-',
              'prefix_tag_distances': {'flowtool-all-0.7.17': 52,
                                       'flowtool-all-0.7.18': 0},
              'tag_version': {'normalized': '0.7.18',
                              'release': (0, 7, 18),
                              'version': '0.7.18'}},
 'version': '0.7.18'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
