"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'f3b81ce845dcf7bc3b69ae47bfd761ed85e9fef0',
              'dirt': '',
              'latest_tag': 'flowtool-versioning-0.7.33',
              'latest_tag_commit': 'f3b81ce845dcf7bc3b69ae47bfd761ed85e9fef0',
              'latest_tag_version': '0.7.33',
              'prefix': 'flowtool-versioning-',
              'prefix_tag_distances': {'flowtool-versioning-0.7.11': 167,
                                       'flowtool-versioning-0.7.12': 166,
                                       'flowtool-versioning-0.7.13': 165,
                                       'flowtool-versioning-0.7.14': 163,
                                       'flowtool-versioning-0.7.15': 162,
                                       'flowtool-versioning-0.7.16': 159,
                                       'flowtool-versioning-0.7.17': 157,
                                       'flowtool-versioning-0.7.18': 155,
                                       'flowtool-versioning-0.7.19': 154,
                                       'flowtool-versioning-0.7.20': 152,
                                       'flowtool-versioning-0.7.21': 149,
                                       'flowtool-versioning-0.7.22': 137,
                                       'flowtool-versioning-0.7.23': 130,
                                       'flowtool-versioning-0.7.24': 129,
                                       'flowtool-versioning-0.7.25': 127,
                                       'flowtool-versioning-0.7.26': 126,
                                       'flowtool-versioning-0.7.27': 116,
                                       'flowtool-versioning-0.7.28': 114,
                                       'flowtool-versioning-0.7.29': 111,
                                       'flowtool-versioning-0.7.30': 108,
                                       'flowtool-versioning-0.7.31': 107,
                                       'flowtool-versioning-0.7.32': 81,
                                       'flowtool-versioning-0.7.33': 0},
              'tag_version': {'normalized': '0.7.33',
                              'release': (0, 7, 33),
                              'version': '0.7.33'}},
 'version': '0.7.33'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
