# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: epsilon/solver_params.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='epsilon/solver_params.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1b\x65psilon/solver_params.proto\"\xb2\x06\n\x0cSolverParams\x12\x18\n\ttolerance\x18\x01 \x01(\x01:\x05\x30.001\x12\x1d\n\x0emax_iterations\x18\x02 \x01(\x05:\x05\x31\x30\x30\x30\x30\x12\x18\n\nblock_size\x18\n \x01(\x05:\x04\x31\x30\x30\x30\x12\x0e\n\x03rho\x18\x0b \x01(\x01:\x01\x31\x12\x18\n\tnormalize\x18\x0c \x01(\x08:\x05\x66\x61lse\x12\x16\n\x07verbose\x18\x1b \x01(\x08:\x05\x66\x61lse\x12\x16\n\tscs_alpha\x18\x03 \x01(\x01:\x03\x31.5\x12\x18\n\tscs_rho_x\x18\x04 \x01(\x01:\x05\x30.001\x12\x1b\n\rscs_normalize\x18\x05 \x01(\x08:\x04true\x12\x1e\n\x13scs_normalize_scale\x18\x06 \x01(\x01:\x01\x35\x12\x1e\n\x0fscs_cg_best_tol\x18\x07 \x01(\x01:\x05\x31\x65-09\x12\x1b\n\x0escs_cg_min_tol\x18\x08 \x01(\x01:\x03\x30.1\x12\x16\n\x0bscs_cg_rate\x18\t \x01(\x01:\x01\x32\x12\x15\n\x07rel_tol\x18\r \x01(\x01:\x04\x30.01\x12\x17\n\x07\x61\x62s_tol\x18\x0e \x01(\x01:\x06\x30.0001\x12\x1b\n\x10\x61lpha_relaxation\x18\x10 \x01(\x01:\x01\x31\x12 \n\x12\x64\x65sired_block_size\x18\x0f \x01(\x05:\x04\x31\x30\x30\x30\x12\x17\n\nkappa_rate\x18\x11 \x01(\x01:\x03\x31.5\x12\x1c\n\x10\x65poch_iterations\x18\x12 \x01(\x05:\x02\x31\x30\x12\x1b\n\x0elog_iterations\x18\x1c \x01(\x05:\x03\x31\x30\x30\x12\x1a\n\x0f\x63onsensus_scale\x18\x13 \x01(\x01:\x01\x31\x12\x1e\n\x0epush_tolerance\x18\x15 \x01(\x01:\x06\x30.0001\x12\x1d\n\x10\x64\x65\x62ug_iterations\x18\x16 \x01(\x05:\x03\x31\x30\x30\x12\x18\n\tmin_scale\x18\x17 \x01(\x01:\x05\x30.001\x12\'\n\x18ignore_stopping_criteria\x18\x18 \x01(\x08:\x05\x66\x61lse\x12$\n\x19\x63onsensus_rate_limit_usec\x18\x19 \x01(\x05:\x01\x30\x12&\n\x16status_rate_limit_usec\x18\x1a \x01(\x05:\x06\x31\x30\x30\x30\x30\x30\x12\x1a\n\x0cuse_epigraph\x18\x1d \x01(\x08:\x04true')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SOLVERPARAMS = _descriptor.Descriptor(
  name='SolverParams',
  full_name='SolverParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tolerance', full_name='SolverParams.tolerance', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0.001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_iterations', full_name='SolverParams.max_iterations', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='block_size', full_name='SolverParams.block_size', index=2,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rho', full_name='SolverParams.rho', index=3,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normalize', full_name='SolverParams.normalize', index=4,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='verbose', full_name='SolverParams.verbose', index=5,
      number=27, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scs_alpha', full_name='SolverParams.scs_alpha', index=6,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=1.5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scs_rho_x', full_name='SolverParams.scs_rho_x', index=7,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0.001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scs_normalize', full_name='SolverParams.scs_normalize', index=8,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scs_normalize_scale', full_name='SolverParams.scs_normalize_scale', index=9,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scs_cg_best_tol', full_name='SolverParams.scs_cg_best_tol', index=10,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=1e-09,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scs_cg_min_tol', full_name='SolverParams.scs_cg_min_tol', index=11,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0.1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scs_cg_rate', full_name='SolverParams.scs_cg_rate', index=12,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rel_tol', full_name='SolverParams.rel_tol', index=13,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0.01,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='abs_tol', full_name='SolverParams.abs_tol', index=14,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0.0001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alpha_relaxation', full_name='SolverParams.alpha_relaxation', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='desired_block_size', full_name='SolverParams.desired_block_size', index=16,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kappa_rate', full_name='SolverParams.kappa_rate', index=17,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=1.5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='epoch_iterations', full_name='SolverParams.epoch_iterations', index=18,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_iterations', full_name='SolverParams.log_iterations', index=19,
      number=28, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='consensus_scale', full_name='SolverParams.consensus_scale', index=20,
      number=19, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='push_tolerance', full_name='SolverParams.push_tolerance', index=21,
      number=21, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0.0001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='debug_iterations', full_name='SolverParams.debug_iterations', index=22,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_scale', full_name='SolverParams.min_scale', index=23,
      number=23, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0.001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ignore_stopping_criteria', full_name='SolverParams.ignore_stopping_criteria', index=24,
      number=24, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='consensus_rate_limit_usec', full_name='SolverParams.consensus_rate_limit_usec', index=25,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_rate_limit_usec', full_name='SolverParams.status_rate_limit_usec', index=26,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=100000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_epigraph', full_name='SolverParams.use_epigraph', index=27,
      number=29, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=850,
)

DESCRIPTOR.message_types_by_name['SolverParams'] = _SOLVERPARAMS

SolverParams = _reflection.GeneratedProtocolMessageType('SolverParams', (_message.Message,), dict(
  DESCRIPTOR = _SOLVERPARAMS,
  __module__ = 'epsilon.solver_params_pb2'
  # @@protoc_insertion_point(class_scope:SolverParams)
  ))
_sym_db.RegisterMessage(SolverParams)


# @@protoc_insertion_point(module_scope)
