"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '5981d28670527d26233190c5bc0f5fcb6d4e6abb',
              'dirt': '',
              'latest_tag': 'flowtool-demo-githooks-0.7.9',
              'latest_tag_commit': '5981d28670527d26233190c5bc0f5fcb6d4e6abb',
              'latest_tag_version': '0.7.9',
              'prefix': 'flowtool-demo-githooks-',
              'prefix_tag_distances': {'flowtool-demo-githooks-0.7.6': 96,
                                       'flowtool-demo-githooks-0.7.7': 73,
                                       'flowtool-demo-githooks-0.7.8': 6,
                                       'flowtool-demo-githooks-0.7.9': 0},
              'tag_version': {'normalized': '0.7.9',
                              'release': (0, 7, 9),
                              'version': '0.7.9'}},
 'version': '0.7.9'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
