"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '53814a962c4f3023b3ea9a4e8dd66cd89fac0454',
              'dirt': '',
              'latest_tag': 'flowtool-python-0.7.17',
              'latest_tag_commit': '53814a962c4f3023b3ea9a4e8dd66cd89fac0454',
              'latest_tag_version': '0.7.17',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.11': 103,
                                       'flowtool-python-0.7.12': 98,
                                       'flowtool-python-0.7.13': 96,
                                       'flowtool-python-0.7.14': 5,
                                       'flowtool-python-0.7.15': 2,
                                       'flowtool-python-0.7.16': 1,
                                       'flowtool-python-0.7.17': 0},
              'tag_version': {'normalized': '0.7.17',
                              'release': (0, 7, 17),
                              'version': '0.7.17'}},
 'version': '0.7.17'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
