#
# HOLOCRON CONFIGURATION FILE.
#
# FOR MORE DETAILS AND OPTIONS, PLEASE VISIT THE SETTINGS DOCUMENTATION
# PAGE - https://holocron.readthedocs.org/en/latest/settings.html
#

site:
  title: Kenobi's Thoughts
  author: Obi-Wan Kenobi
  url: http://obi-wan.jedi

theme:
  navigation: !!pairs
    - about: /about
    - feed: /feed.xml

  copyright: >
    &copy; 19 BBY, Obi-Wan Kenobi

ext:
  enabled:
    - markdown
    - restructuredtext
    - index
    - feed
    - sitemap
    - tags
