"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': 'ff1b7b318ee033285f1f527906c7696732e67027',
              'dirt': '',
              'latest_tag': 'flowtool-githooks-0.7.21',
              'latest_tag_commit': 'ff1b7b318ee033285f1f527906c7696732e67027',
              'latest_tag_version': '0.7.21',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {'flowtool-githooks-0.7.13': 116,
                                       'flowtool-githooks-0.7.14': 93,
                                       'flowtool-githooks-0.7.15': 47,
                                       'flowtool-githooks-0.7.16': 39,
                                       'flowtool-githooks-0.7.17': 38,
                                       'flowtool-githooks-0.7.18': 37,
                                       'flowtool-githooks-0.7.19': 34,
                                       'flowtool-githooks-0.7.20': 13,
                                       'flowtool-githooks-0.7.21': 0,
                                       'flowtool-githooks-demo-0.7.4': 87,
                                       'flowtool-githooks-demo-0.7.5': 86},
              'tag_version': {'normalized': '0.7.21',
                              'release': (0, 7, 21),
                              'version': '0.7.21'}},
 'version': '0.7.21'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
