__version__ = "0.0.1"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = 'develop'
__git_remote_tracking_branch__ = 'origin/develop'
__git_remote_url__ = 'git@git.infinidat.com:host-opensource/dnssimple.git'
__git_head_hash__ = '2a8a796442f405ffc7b2b2dae486f360ccc3e46a'
__git_head_subject__ = 'Finished Release v0.0.1'
__git_head_message__ = '* develop:\n  ddns script\n  added all project files'
__git_dirty_diff__ = ''
__git_commit_date__ = '2016-04-10 16:10:40'
