"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '56049d3d80abe10ba3fe455bcbedc1765fa4308f',
              'dirt': '',
              'latest_tag': 'flowtool-versioning-0.7.30',
              'latest_tag_commit': '56049d3d80abe10ba3fe455bcbedc1765fa4308f',
              'latest_tag_version': '0.7.30',
              'prefix': 'flowtool-versioning-',
              'prefix_tag_distances': {'flowtool-versioning-0.7.27': 8,
                                       'flowtool-versioning-0.7.28': 6,
                                       'flowtool-versioning-0.7.29': 3,
                                       'flowtool-versioning-0.7.30': 0},
              'tag_version': {'normalized': '0.7.30',
                              'release': (0, 7, 30),
                              'version': '0.7.30'}},
 'version': '0.7.30'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
