
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a19d10f0a1c8e51399eb7e6c19b0acb3b4fc5f2e",
 "version": "0.3.post6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
