"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '52b5e7c12344e9086e3d33bba4af82bee58631cc',
              'dirt': '',
              'latest_tag': 'data-pypes-0.1.8',
              'latest_tag_commit': '52b5e7c12344e9086e3d33bba4af82bee58631cc',
              'latest_tag_version': '0.1.8',
              'prefix': 'data-pypes-',
              'prefix_tag_distances': {'data-pypes-0.1.1': 27,
                                       'data-pypes-0.1.2': 25,
                                       'data-pypes-0.1.3': 23,
                                       'data-pypes-0.1.4': 18,
                                       'data-pypes-0.1.5': 12,
                                       'data-pypes-0.1.6': 10,
                                       'data-pypes-0.1.7': 3,
                                       'data-pypes-0.1.8': 0},
              'tag_version': {'normalized': '0.1.8',
                              'release': (0, 1, 8),
                              'version': '0.1.8'}},
 'version': '0.1.8'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
