
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "41316abe370500c38a7cf23517d135e7af765b0f",
 "version": "0.3.post7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
