language: python
python:
  - "3.4"
  - "2.7"
install: pip install -U -r requirements.txt -r test-requirements.txt
before_script: flake8 --ignore=E123,E125,H904,H405,H404,H305,H306,H307
script: ostestr
cache:
    directories:
        - $HOME/.cache/pip
