
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0adeb9e01c50f5786ad2bdfa1e91010082ba8e09",
 "version": "1.1.43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
