"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': u'011a4da7a188af2ca050cd2849a2ddfb92d15ff6',
              'dirt': u'',
              'latest_tag': u'flowtool-versioning-0.7.21',
              'latest_tag_commit': u'011a4da7a188af2ca050cd2849a2ddfb92d15ff6',
              'latest_tag_version': u'0.7.21',
              'prefix': 'flowtool-versioning-',
              'prefix_tag_distances': {u'flowtool-versioning-0.7.11': 18,
                                       u'flowtool-versioning-0.7.12': 17,
                                       u'flowtool-versioning-0.7.13': 16,
                                       u'flowtool-versioning-0.7.14': 14,
                                       u'flowtool-versioning-0.7.15': 13,
                                       u'flowtool-versioning-0.7.16': 10,
                                       u'flowtool-versioning-0.7.17': 8,
                                       u'flowtool-versioning-0.7.18': 6,
                                       u'flowtool-versioning-0.7.19': 5,
                                       u'flowtool-versioning-0.7.20': 3,
                                       u'flowtool-versioning-0.7.21': 0},
              'tag_version': {'normalized': '0.7.21',
                              'release': (0, 7, 21),
                              'version': u'0.7.21'}},
 'version': u'0.7.21'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
