# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.NullBooleanField(),
        ),
    ]
