---
meta:
    description:
        Creates a set of Kinesis streams
    parameters:
        streams:
            description:
                The names and shard counts for each stream
            value:
                - name: Stream
                  shard_count: 1
