"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '2852b17ca8ab2c9914d9672798d4ce86de916bfb',
              'dirt': '',
              'latest_tag': 'flowtool-githooks-0.7.16',
              'latest_tag_commit': '2852b17ca8ab2c9914d9672798d4ce86de916bfb',
              'latest_tag_version': '0.7.16',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {'flowtool-githooks-0.7.13': 77,
                                       'flowtool-githooks-0.7.14': 54,
                                       'flowtool-githooks-0.7.15': 8,
                                       'flowtool-githooks-0.7.16': 0},
              'tag_version': {'normalized': '0.7.16',
                              'release': (0, 7, 16),
                              'version': '0.7.16'}},
 'version': '0.7.16'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
