"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': '67c09b2d100b6472a562cd2d0b410a0617bc1629',
              'dirt': '',
              'latest_tag': 'flowtool-demo-githooks-0.7.7',
              'latest_tag_commit': '67c09b2d100b6472a562cd2d0b410a0617bc1629',
              'latest_tag_version': '0.7.7',
              'prefix': 'flowtool-demo-githooks-',
              'prefix_tag_distances': {'flowtool-demo-githooks-0.7.6': 23,
                                       'flowtool-demo-githooks-0.7.7': 0},
              'tag_version': {'normalized': '0.7.7',
                              'release': (0, 7, 7),
                              'version': '0.7.7'}},
 'version': '0.7.7'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
