package:
  name: {{base.pkg_full_name, }}
  version: "{{key, version.major}}.{{key, version.minor}}.{{key, version.post}}"

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  summary: "{{key, doc.description}}"
  license: "{{key, license.name}}"
  license_file: LICENSE
