site_name: CRUSH HA Documentation
site_description: Python implementation of CRUSH maps from ceph.com
site_author: Da_Blitz
repo_url: http://blitz.works/crushha/
repo_name: CRUSHHA src
theme: cyborg
pages:
 - index.md
 - Usage:
   - Installation.md
   - Examples.md
   - API.md
 - Changelog.rst
copyright: 'Copyright: Da_Blitz (2016)'
