
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3873b9400bc12ba59aa0b29723f25fc2cb5d6db0",
 "version": "0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
