
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "62464d10117f66957bf6828e699f26113019ca7d",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
