# -*- coding: utf-8 -*-
# This file has been autogenerated by the pywayland scanner

# Copyright © 2008-2011 Kristian Høgsberg
# Copyright © 2010-2011 Intel Corporation
# Copyright © 2012-2013 Collabora, Ltd.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice (including the
# next paragraph) shall be included in all copies or substantial
# portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from .display import Display  # noqa
from .registry import Registry  # noqa
from .callback import Callback  # noqa
from .compositor import Compositor  # noqa
from .shmpool import ShmPool  # noqa
from .shm import Shm  # noqa
from .buffer import Buffer  # noqa
from .dataoffer import DataOffer  # noqa
from .datasource import DataSource  # noqa
from .datadevice import DataDevice  # noqa
from .datadevicemanager import DataDeviceManager  # noqa
from .shell import Shell  # noqa
from .shellsurface import ShellSurface  # noqa
from .surface import Surface  # noqa
from .seat import Seat  # noqa
from .pointer import Pointer  # noqa
from .keyboard import Keyboard  # noqa
from .touch import Touch  # noqa
from .output import Output  # noqa
from .region import Region  # noqa
from .subcompositor import Subcompositor  # noqa
from .subsurface import Subsurface  # noqa
