"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'f3b81ce845dcf7bc3b69ae47bfd761ed85e9fef0',
              'dirt': '',
              'latest_tag': 'flowtool-all-0.7.12',
              'latest_tag_commit': 'f3b81ce845dcf7bc3b69ae47bfd761ed85e9fef0',
              'latest_tag_version': '0.7.12',
              'prefix': 'flowtool-all-',
              'prefix_tag_distances': {'flowtool-all-0.7.10': 88,
                                       'flowtool-all-0.7.11': 82,
                                       'flowtool-all-0.7.12': 0,
                                       'flowtool-all-0.7.7': 160,
                                       'flowtool-all-0.7.8': 150,
                                       'flowtool-all-0.7.9': 110},
              'tag_version': {'normalized': '0.7.12',
                              'release': (0, 7, 12),
                              'version': '0.7.12'}},
 'version': '0.7.12'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
