"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '607d15c25bfc3871f94f62a979d1e0c25e21c0ad',
              'dirt': '',
              'latest_tag': 'flowtool-all-0.7.16',
              'latest_tag_commit': '607d15c25bfc3871f94f62a979d1e0c25e21c0ad',
              'latest_tag_version': '0.7.16',
              'prefix': 'flowtool-all-',
              'prefix_tag_distances': {'flowtool-all-0.7.10': 196,
                                       'flowtool-all-0.7.11': 190,
                                       'flowtool-all-0.7.12': 108,
                                       'flowtool-all-0.7.13': 3,
                                       'flowtool-all-0.7.14': 2,
                                       'flowtool-all-0.7.15': 1,
                                       'flowtool-all-0.7.16': 0},
              'tag_version': {'normalized': '0.7.16',
                              'release': (0, 7, 16),
                              'version': '0.7.16'}},
 'version': '0.7.16'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
