
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1a860ca630ea99238cf2d70d2aa7925a1696cfa7",
 "version": "0.0.18-1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
