"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'b9be230206cdda4c47fb7dccd83d14c86f320a88',
              'dirt': '',
              'latest_tag': 'flowtool-versioning-0.7.42',
              'latest_tag_commit': 'b9be230206cdda4c47fb7dccd83d14c86f320a88',
              'latest_tag_version': '0.7.42',
              'prefix': 'flowtool-versioning-',
              'prefix_tag_distances': {'flowtool-versioning-0.7.39': 43,
                                       'flowtool-versioning-0.7.40': 42,
                                       'flowtool-versioning-0.7.41': 7,
                                       'flowtool-versioning-0.7.42': 0},
              'tag_version': {'normalized': '0.7.42',
                              'release': (0, 7, 42),
                              'version': '0.7.42'}},
 'version': '0.7.42'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
