language: python
sudo: false
cache: pip

python:
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - pip install codecov

install:
  - pip install -r requirements.txt -r test-requirements.txt
  - pip install -U pip setuptools
  - python setup.py develop

script:
  - py.test --cov-fail-under 90
  - flake8
  - radon cc --average --show-closures concierge
  - radon raw --summary concierge
  - radon mi --show --multi concierge
  - xenon -aA -mA -bB concierge

after_success:
  - codecov

notifications:
  email:
    - nineseconds@yandex.ru
