# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microbot', '0010_auto_20160330_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microbot.Request'),
        ),
    ]
