
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d77449d92e38736ca302328619517407568082b8",
 "version": "0.2.post17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
