"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'e13908c50511b80b097e508c69e360a3e9a635d2',
              'dirt': '',
              'latest_tag': 'flowtool-base-0.7.46',
              'latest_tag_commit': 'e13908c50511b80b097e508c69e360a3e9a635d2',
              'latest_tag_version': '0.7.46',
              'prefix': 'flowtool-base-',
              'prefix_tag_distances': {'flowtool-base-0.7.43': 39,
                                       'flowtool-base-0.7.44': 38,
                                       'flowtool-base-0.7.45': 19,
                                       'flowtool-base-0.7.46': 0},
              'tag_version': {'normalized': '0.7.46',
                              'release': (0, 7, 46),
                              'version': '0.7.46'}},
 'version': '0.7.46'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
