
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d5920a29c71561c7e0ac0c65619a9c0eb2a0ac1b",
 "version": "1.0.0.post.dev119"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
