rules:
- name: sample-rule-name
  description: This is a sample CloudWatchEvent
  schedule: rate(5 minutes)
  targets:
  - id: sample-target-1
    input:
      this:
      - is: a
      - sample: input
#    input_path: json.path.format
