sudo: false
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script: "nosetests -v --with-coverage --cover-package=lamvery"
after_success: coveralls
