# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microbot', '0004_auto_20160311_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_template', models.TextField(verbose_name='Text template')),
                ('keyboard_template', models.TextField(blank=True, null=True, verbose_name='Keyboard template')),
            ],
        ),
        migrations.RemoveField(
            model_name='handler',
            name='response_keyboard_template',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='response_text_template',
        ),
        migrations.AddField(
            model_name='handler',
            name='response',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='microbot.Response'),
            preserve_default=False,
        ),
    ]
