# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import microbot.models.bot


class Migration(migrations.Migration):

    dependencies = [
        ('microbot', '0006_auto_20160316_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='handler',
            name='name',
            field=models.CharField(db_index=True, default='namehandler', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hook',
            name='name',
            field=models.CharField(db_index=True, default='namehook', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='chat_id',
            field=models.BigIntegerField(db_index=True, default=123, verbose_name='Chat id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='name',
            field=models.CharField(db_index=True, default='namerecipient', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(db_index=True, max_length=100, validators=[microbot.models.bot.validate_token], verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
