# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microbot', '0015_auto_20160404_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='request',
            field=models.OneToOneField(blank=True, help_text='Request the Handler processes.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='microbot.Request'),
        ),
    ]
