# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflowapp', '0005_auto_20160308_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignee',
            name='assigned_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
