# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0007_auto_20160309_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='allow_access',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='deny_access',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
