
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5dce64b3f992cb5ffba9225ee281f12398da0822",
 "version": "1.10.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
