
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8814132d5cb1a9df604fc78541f293348ead9a05",
 "version": "16.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
