"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'd7990f71257d84c702efab9dbe42ecde7d8a0645',
              'dirt': '',
              'latest_tag': 'flowtool-demo-githooks-0.7.19',
              'latest_tag_commit': 'd7990f71257d84c702efab9dbe42ecde7d8a0645',
              'latest_tag_version': '0.7.19',
              'prefix': 'flowtool-demo-githooks-',
              'prefix_tag_distances': {'flowtool-demo-githooks-0.7.17': 127,
                                       'flowtool-demo-githooks-0.7.18': 3,
                                       'flowtool-demo-githooks-0.7.19': 0},
              'tag_version': {'normalized': '0.7.19',
                              'release': (0, 7, 19),
                              'version': '0.7.19'}},
 'version': '0.7.19'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
