"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'vcs_info': {'commit': u'7c73532b44c0074a0fc4f49c502bbc48e456d172',
              'dirt': u'',
              'latest_tag': u'flowtool-versioning-0.7.20',
              'latest_tag_commit': u'7c73532b44c0074a0fc4f49c502bbc48e456d172',
              'latest_tag_version': u'0.7.20',
              'prefix': 'flowtool-versioning-',
              'prefix_tag_distances': {u'flowtool-versioning-0.7.11': 15,
                                       u'flowtool-versioning-0.7.12': 14,
                                       u'flowtool-versioning-0.7.13': 13,
                                       u'flowtool-versioning-0.7.14': 11,
                                       u'flowtool-versioning-0.7.15': 10,
                                       u'flowtool-versioning-0.7.16': 7,
                                       u'flowtool-versioning-0.7.17': 5,
                                       u'flowtool-versioning-0.7.18': 3,
                                       u'flowtool-versioning-0.7.19': 2,
                                       u'flowtool-versioning-0.7.20': 0},
              'tag_version': {'normalized': '0.7.20',
                              'release': (0, 7, 20),
                              'version': u'0.7.20'}},
 'version': u'0.7.20'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
