"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'f3b81ce845dcf7bc3b69ae47bfd761ed85e9fef0',
              'dirt': '',
              'latest_tag': 'flowtool-releasing-0.7.11',
              'latest_tag_commit': 'f3b81ce845dcf7bc3b69ae47bfd761ed85e9fef0',
              'latest_tag_version': '0.7.11',
              'prefix': 'flowtool-releasing-',
              'prefix_tag_distances': {'flowtool-releasing-0.7.10': 36,
                                       'flowtool-releasing-0.7.11': 0,
                                       'flowtool-releasing-0.7.5': 84,
                                       'flowtool-releasing-0.7.6': 83,
                                       'flowtool-releasing-0.7.7': 79,
                                       'flowtool-releasing-0.7.8': 67,
                                       'flowtool-releasing-0.7.9': 47},
              'tag_version': {'normalized': '0.7.11',
                              'release': (0, 7, 11),
                              'version': '0.7.11'}},
 'version': '0.7.11'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
