# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0008_auto_20160309_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Precondition',
            new_name='Condition',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='state_id',
        ),
        migrations.AddField(
            model_name='condition',
            name='transition_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflowapp.Transition'),
            preserve_default=False,
        ),
    ]
