__version__ = "0.1.33"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v0.1.33)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '7d488393568b1b5f036c85530c7f097824d1fd3b'
__git_head_subject__ = 'Finished Release v0.1.33'
__git_head_message__ = ''
__git_dirty_diff__ = ''