from Tkinter import *
top = Tk()
# Code to add widgets will go here..
top.geometry('700x700')
frame0 = Frame (top)
frame0.pack(fill = X)
text_frame0 = Label (frame0,text="Lab Automation",height="4",bd="3")
text_frame0.pack()
frame1 = Frame (top)
frame1.pack(fill = Y,side = LEFT)
but0 = Button (frame1,fg="black",text="Assignment",height="3")
but0.pack(side = TOP,fill=X)
but1 = Button (frame1,fg="black",text="Discussions",height="3")
but1.pack(side = TOP,fill=X)
but2 = Button (frame1,fg="black",text="fjdkgdf",height="3")
but2.pack(side = TOP,fill=X)
but3 = Button (frame1,fg="black",text="fjdkgdf",height="3")
but3.pack(side = TOP,fill=X)
top.mainloop()
