"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'a64f67da819c2699ca46ba9338378b7fc407c443',
              'dirt': '',
              'latest_tag': 'flowtool-releasing-0.7.18',
              'latest_tag_commit': 'a64f67da819c2699ca46ba9338378b7fc407c443',
              'latest_tag_version': '0.7.18',
              'prefix': 'flowtool-releasing-',
              'prefix_tag_distances': {'flowtool-releasing-0.7.16': 127,
                                       'flowtool-releasing-0.7.17': 1,
                                       'flowtool-releasing-0.7.18': 0},
              'tag_version': {'normalized': '0.7.18',
                              'release': (0, 7, 18),
                              'version': '0.7.18'}},
 'version': '0.7.18'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
