language: python
python:
  - "2.7"
  - "3.5"
  - "pypy"
install: "pip install -r requirements.txt -r test-requirements.txt"
before_script: python setup.py develop
script: mamba spec/*.py
#after_success: 'coverage report'
cache:
  directories:
    - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
      - maven
